=== paulagolder/jcert/Certificates/Dev/jcerttemplate.dtd
<!ELEMENT sourcedocuments (sourcedocument*)>
<!ELEMENT sourcedocument (template, certificate)>
<!ELEMENT template (templateID , version?, stylesheet ,name?, savefilepattern?, author?, editdate?, type?,country?, period?, source?)>

<!ELEMENT templateID ( #PCDATA) >
<!ELEMENT version ( #PCDATA) >
<!ELEMENT savefilepattern ( #PCDATA) >
<!ELEMENT stylesheet ( #PCDATA) >
<!ELEMENT name ( #PCDATA) >
<!ELEMENT author ( #PCDATA) >
<!ELEMENT editdate ( #PCDATA) >
<!ELEMENT type ( #PCDATA) >
<!ELEMENT country ( #PCDATA) >
<!ELEMENT period ( #PCDATA) >
<!ELEMENT source ( #PCDATA) >

<!ELEMENT certificate (styleblock | hgroup | vgroup | table )* >
<!ATTLIST certificate
name NMTOKEN #IMPLIED
layout NMTOKEN #IMPLIED
objecttype CDATA #IMPLIED
backgroundcolor CDATA #IMPLIED
foregroundcolor CDATA #IMPLIED
borderwidth CDATA #IMPLIED
bordercolor CDATA #IMPLIED
height CDATA #IMPLIED
width CDATA #IMPLIED
tgap CDATA #IMPLIED
lgap CDATA #IMPLIED
rgap CDATA #IMPLIED
bgap CDATA #IMPLIED
hgap CDATA #IMPLIED
vgap CDATA #IMPLIED
gaps CDATA #IMPLIED
>

<!ELEMENT styleblock EMPTY >
<!ATTLIST styleblock
name NMTOKEN #IMPLIED
objecttype CDATA #IMPLIED
backgroundcolor CDATA #IMPLIED
foregroundcolor CDATA #IMPLIED
    bordercolor CDATA #IMPLIED
    borderwidth CDATA #IMPLIED
    font-size NMTOKEN #IMPLIED
    font-style CDATA #IMPLIED
    font-name CDATA #IMPLIED
    height CDATA #IMPLIED
    columns CDATA #IMPLIED
    tgap CDATA #IMPLIED
    lgap CDATA #IMPLIED
    rgap CDATA #IMPLIED
    bgap CDATA #IMPLIED
    hgap CDATA #IMPLIED
    vgap CDATA #IMPLIED
    gaps CDATA #IMPLIED >

    <!ELEMENT hgroup (styleblock | vgroup | hgroup | table  | vblock | hblock )* >
    <!ATTLIST hgroup
    name CDATA #IMPLIED
    layout NMTOKEN #IMPLIED
    objecttype CDATA #IMPLIED
    rows CDATA #IMPLIED
    colspan NMTOKEN #IMPLIED
    rowspan NMTOKEN #IMPLIED
    backgroundcolor CDATA #IMPLIED
    foregroundcolor CDATA #IMPLIED
    bordercolor CDATA #IMPLIED
    borderwidth CDATA #IMPLIED
    height CDATA #IMPLIED
    width CDATA #IMPLIED
    tgap CDATA #IMPLIED
    lgap CDATA #IMPLIED
    rgap CDATA #IMPLIED
    bgap CDATA #IMPLIED
    hgap CDATA #IMPLIED
    vgap CDATA #IMPLIED
    gaps CDATA #IMPLIED
    padding CDATA #IMPLIED
    direction CDATA #IMPLIED
    
    >


    <!ELEMENT vgroup (styleblock  | vgroup | hgroup | table | vblock | hblock )* >
    <!ATTLIST vgroup
    name CDATA #IMPLIED
    layout NMTOKEN #IMPLIED
    colspan NMTOKEN #IMPLIED
    rowspan NMTOKEN #IMPLIED
    objecttype CDATA #IMPLIED
    backgroundcolor CDATA #IMPLIED
    foregroundcolor CDATA #IMPLIED
    bordercolor CDATA #IMPLIED
    borderwidth CDATA #IMPLIED
    height CDATA #IMPLIED
    width CDATA #IMPLIED
    tgap CDATA #IMPLIED
    lgap CDATA #IMPLIED
    rgap CDATA #IMPLIED
    bgap CDATA #IMPLIED
    hgap CDATA #IMPLIED
    vgap CDATA #IMPLIED
    gaps CDATA #IMPLIED
    align CDATA #IMPLIED
    padding CDATA #IMPLIED
        >

        

    <!ELEMENT vblock (styleblock  |  vblock | hblock | label | input  )* >
    <!ATTLIST vblock
    name CDATA #IMPLIED
    layout NMTOKEN #IMPLIED
    colspan NMTOKEN #IMPLIED
    rowspan NMTOKEN #IMPLIED
    objecttype CDATA #IMPLIED
    backgroundcolor CDATA #IMPLIED
    foregroundcolor CDATA #IMPLIED
    bordercolor CDATA #IMPLIED
    borderwidth CDATA #IMPLIED
    height CDATA #IMPLIED
    width CDATA #IMPLIED
    tgap CDATA #IMPLIED
    lgap CDATA #IMPLIED
    rgap CDATA #IMPLIED
    bgap CDATA #IMPLIED
    hgap CDATA #IMPLIED
    vgap CDATA #IMPLIED
    gaps CDATA #IMPLIED
    align CDATA #IMPLIED
        >
    
    
    <!ELEMENT hblock (styleblock  |  vblock | hblock | label | input  )* >
    <!ATTLIST hblock
    name CDATA #IMPLIED
     align NMTOKEN #IMPLIED
    layout NMTOKEN #IMPLIED
    colspan NMTOKEN #IMPLIED
    rowspan NMTOKEN #IMPLIED
    objecttype CDATA #IMPLIED
    backgroundcolor CDATA #IMPLIED
    foregroundcolor CDATA #IMPLIED
        bordercolor CDATA #IMPLIED
        borderwidth CDATA #IMPLIED
        height CDATA #IMPLIED
        width CDATA #IMPLIED
        tgap CDATA #IMPLIED
        lgap CDATA #IMPLIED
        rgap CDATA #IMPLIED
        bgap CDATA #IMPLIED
        hgap CDATA #IMPLIED
        vgap CDATA #IMPLIED
        gaps CDATA #IMPLIED
        >

<!ELEMENT table (styleblock | trow )* >
<!ATTLIST table
        name CDATA #IMPLIED
        layout NMTOKEN #IMPLIED
        objecttype CDATA #IMPLIED
        backgroundcolor CDATA #IMPLIED
        foregroundcolor CDATA #IMPLIED
        borderwidth CDATA #IMPLIED
        bordercolor CDATA #IMPLIED
        height CDATA #IMPLIED
        width CDATA #IMPLIED
        tgap CDATA #IMPLIED
        lgap CDATA #IMPLIED
        rgap CDATA #IMPLIED
        bgap CDATA #IMPLIED
        hgap CDATA #IMPLIED
        vgap CDATA #IMPLIED
        gaps CDATA #IMPLIED
>

<!ELEMENT trow (styleblock | tcell | tcolumn )* >
<!ATTLIST trow
        name CDATA #IMPLIED
        layout NMTOKEN #IMPLIED
        objecttype CDATA #IMPLIED
        rows CDATA #IMPLIED
        backgroundcolor CDATA #IMPLIED
        foregroundcolor CDATA #IMPLIED
            borderwidth CDATA #IMPLIED
            bordercolor CDATA #IMPLIED
            height CDATA #IMPLIED
            width CDATA #IMPLIED
            tgap CDATA #IMPLIED
            lgap CDATA #IMPLIED
            rgap CDATA #IMPLIED
            bgap CDATA #IMPLIED
            hgap CDATA #IMPLIED
            vgap CDATA #IMPLIED
            gaps CDATA #IMPLIED
            >

<!ELEMENT tcell (styleblock | hblock| vblock | label | input )* >
<!ATTLIST tcell
            name CDATA #IMPLIED
            layout NMTOKEN #IMPLIED
            objecttype CDATA #IMPLIED
            backgroundcolor CDATA #IMPLIED
            foregroundcolor CDATA #IMPLIED
            borderwidth CDATA #IMPLIED
            bordercolor CDATA #IMPLIED
            height CDATA #IMPLIED
            width CDATA #IMPLIED
            tgap CDATA #IMPLIED
            lgap CDATA #IMPLIED
            rgap CDATA #IMPLIED
            bgap CDATA #IMPLIED
            hgap CDATA #IMPLIED
            vgap CDATA #IMPLIED
            gaps CDATA #IMPLIED
            align NMTOKEN #IMPLIED
            >

<!ELEMENT tcolumn (styleblock | tcell | trow )* >
<!ATTLIST tcolumn
            name CDATA #IMPLIED
            layout NMTOKEN #IMPLIED
            objecttype CDATA #IMPLIED
            backgroundcolor CDATA #IMPLIED
            foregroundcolor CDATA #IMPLIED
                borderwidth CDATA #IMPLIED
                bordercolor CDATA #IMPLIED
                height CDATA #IMPLIED
                width CDATA #IMPLIED
                tgap CDATA #IMPLIED
                lgap CDATA #IMPLIED
                rgap CDATA #IMPLIED
                bgap CDATA #IMPLIED
                hgap CDATA #IMPLIED
                vgap CDATA #IMPLIED
                gaps CDATA #IMPLIED
                >

 
<!ELEMENT input EMPTY >
<!ATTLIST input
                name CDATA #IMPLIED
                target CDATA #REQUIRED
                value  CDATA #IMPLIED
                layout NMTOKEN #IMPLIED
                objecttype CDATA #IMPLIED
                backgroundcolor CDATA #IMPLIED
                foregroundcolor CDATA #IMPLIED
                font-size NMTOKEN #IMPLIED
                font-style CDATA #IMPLIED
                font-name CDATA #IMPLIED
                bordercolor CDATA #IMPLIED
                borderwidth CDATA #IMPLIED
                columns CDATA #IMPLIED
                height CDATA #IMPLIED
                width CDATA #IMPLIED
                tgap CDATA #IMPLIED
                lgap CDATA #IMPLIED
                rgap CDATA #IMPLIED
                bgap CDATA #IMPLIED
                hgap CDATA #IMPLIED
                vgap CDATA #IMPLIED
                gaps CDATA #IMPLIED
                align CDATA #IMPLIED
                >


<!ELEMENT label ( #PCDATA | text )* >
<!ATTLIST label
                name CDATA #IMPLIED
                align NMTOKEN #IMPLIED
                verticalalign NMTOKEN #IMPLIED
                layout NMTOKEN #IMPLIED
                direction CDATA #IMPLIED
                colspan NMTOKEN #IMPLIED
                rowspan NMTOKEN #IMPLIED
                backgroundcolor CDATA #IMPLIED
                foregroundcolor CDATA #IMPLIED
                    borderwidth CDATA #IMPLIED
                    bordercolor CDATA #IMPLIED
                    font-size NMTOKEN #IMPLIED
                    font-style CDATA #IMPLIED
                    font-name CDATA #IMPLIED
                    height CDATA #IMPLIED
                    width CDATA #IMPLIED
                    tgap CDATA #IMPLIED
                    lgap CDATA #IMPLIED
                    rgap CDATA #IMPLIED
                    bgap CDATA #IMPLIED
                    hgap CDATA #IMPLIED
                    vgap CDATA #IMPLIED
                    gaps CDATA #IMPLIED
                    >
                    
 <!ELEMENT text (#PCDATA )>
 <!ATTLIST text
                    font-size NMTOKEN #IMPLIED
                     backgroundcolor CDATA #IMPLIED
 >

=== paulagolder/jcert/Certificates/Dev/GROMarriageCertCopy_template.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE sourcedocuments  PUBLIC "-//Paul Golder//DTD jcerttemplate//EN" "http://lerot.org/Templates/jcerttemplate.dtd">


<sourcedocuments>
    <sourcedocument>
        <template>
            <templateID>engmarriage20090415</templateID>
            <stylesheet>Templates/GROMarriageCertCopy_stylesheet.xsl</stylesheet>
            <name>GRO Copy of an entry of marriage</name>
            <savefilepattern>gromarriage.xml</savefilepattern>
            <author>Paul A Golder</author>
            <editdate>13 April 2009</editdate>
            <type>Marriage certificate</type>
            <country>England</country>
            <period>1841-</period>
            <source>gro</source>
        </template>
        <certificate  objecttype="certificate" name="main"  backgroundcolor="#CEF6CE" >    
            <styleblock name="inputcell"  bordercolor="gray"  borderwidth="1"  backgroundcolor="#E4DCDC"  />
            <hgroup name="heading"  >  
                <vblock>
                    <label  font-size="16"  foregroundcolor="#04B404" >UK Certified Copy of an entry of Marriage</label>
                </vblock> 
                <vblock >
                </vblock>
                <vgroup align="left">
                    <hblock name ="given"> 
                        <label align="right"  name ="reg"   font-size="16"  foregroundcolor="#04B404" >Given at the General Register Office</label>
                    </hblock>
                    <hblock>
                        <label font-style="italic"   foregroundcolor="black" > Application Number</label>
                        <input target="applicationNumber"   width="60" />
                    </hblock>
                </vgroup>
            </hgroup>         
            <hgroup height="50" />
            <hgroup objecttype="marriage"  borderwidth="0" >
                <vgroup name="registrationlocation">
                    <hblock>
                        <input   target="year"  />
                        <label>Marriage Solemnized at </label>
                        <input   target="location1"/>
                        <label>in the</label>
                        <input   target="location2"  />
                        <label>of</label>
                        <input   target="location3"  />
                        <label>in the county of</label>
                        <input   target="location4"  />
                    </hblock>
                </vgroup>
            </hgroup>
            <hgroup height="30"/>
            <table   name="marriage" objecttype="marriage"  >
                <trow   rows="1"  >
                    <tcell>
                        <label>No.</label>
                    </tcell>
                    <tcell>
                        <label>When Married</label>
                    </tcell>
                    <tcell>
                        <label>Name and Surname</label>
                    </tcell>
                    <tcell>
                        <label>age</label>
                    </tcell>
                    <tcell>
                        <label>condition</label>
                    </tcell>
                    <tcell>
                        <label>Rank or Profession</label>
                    </tcell>
                    <tcell>
                        <label>Residence at time of marriage</label>
                    </tcell>
                    <tcell>
                        <label>Fathers name and Surname</label>               
                    </tcell>
                    <tcell>
                        <label>Rank or Profession of</label>
                        <label>Father</label>
                    </tcell>
                </trow>
                <trow   objecttype="marriage" >
                    <tcell>
                        <input      target="entryno" /> 
                    </tcell>
                    <tcell>
                        <input      target="when" /> 
                    </tcell>
                    <tcell>
                        <input     target="groom.name" /> 
                        <input      target="bride.name" /> 
                    </tcell>
                    <tcell>
                        <input      target="groom.age" /> 
                        <input      target="bride.age" />
                    </tcell>
                    <tcell>
                        <input      target="groom.condition" /> 
                        <input      target="bride.condition" /> 
                    </tcell>
                    <tcell>
                        <input      target="groom.profession" /> 
                        <input      target="bride.profession" /> 
                    </tcell>
                    <tcell>
                        <input      target="groom.residence" /> 
                        <input      target="bride.residence" /> 
                    </tcell>
                    <tcell>          
                        <input      target="groom.father" /> 
                        <input      target="bride.father" /> 
                    </tcell>
                    <tcell>
                        <input      target="groom.fatheroccupation" /> 
                        <input      target="bride.fatheroccupation" /> 
                    </tcell>
                </trow>
            </table>
            <hgroup height="30" />
            <vgroup  name="marriagerites"  objecttype="marriage" >
                <hblock  >            
                    <label>Married in the  </label>
                    <input   target="location5"/>
                    <label>according to the Rites and ceremonies of the Established Church, by</label>
                    <input   target="licence"  />
                    <label>or after</label>
                    <input   target="banns"  />
                    <label>by me</label>
                </hblock>   
                <hblock>
                    <vblock />
                    <input width="100" align="right"  target="official"  />
                </hblock>
            </vgroup>    
            <hgroup height="20" />
            <hgroup name="bottomgroup" direction="horizontal"  objecttype="marriage" >
                <vblock>
                    <label  font-size="10" >
                        <text>This marriage</text>
                        <text>was solemnized</text>
                        <text>between us</text>
                    </label>
                </vblock>
                <vblock objecttype="marriage" >
                    <input      target="groom.signature" /> 
                    <input      target="bride.signature" /> 
                </vblock>
                <vblock>
                    <label  font-size="10" >
                        <text>in the</text>
                        <text>presence</text>
                        <text>of us</text>
                    </label>
                </vblock>
                <vblock>
                    <input      target="witness.first" /> 
                    <input      target="witness.second" /> 
                </vblock>
            </hgroup>       
            <hgroup height="60"   borderwidth="0"  padding="10" />
            <vgroup padding="20" >
                <hblock>
                    <label   foregroundcolor="#04B404" >CERTIFIED to be a true copy of an entry in the certified copy of a Register of Marriages in the Registration Districtof.</label>
                    <input      target="registrationDistrict" /> 
                </hblock>
                <hblock>
                    <label   foregroundcolor="#04B404" >Given at the GENERAL REGISTER OFFICE under the seal of the said Office, the </label>
                    <input target="issue.day" />
                    <label>day of</label>
                    <input target="issue.month" />
                    <input target ="issue.year" />
                </hblock>
            </vgroup>         
            
            <vgroup>
                <hblock>
                    <input target="issue.number"  width="50"/>
                    <label/>
                </hblock>
            </vgroup>
        </certificate>                
    </sourcedocument>
</sourcedocuments>

=== paulagolder/jcert/Certificates/temp/temp_xEngCensus1851_template.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE sourcedocuments  PUBLIC "-//Paul Golder//DTD jcerttemplate2//EN" "http://lerot.org/Templates/jcerttemplate.dtd">

 <sourcedocuments>
   <sourcedocument>
     <template>
       <templateID>Census1851</templateID>
       <version>3</version>
       <stylesheet>../Stylesheets/EngCensus1851_stylesheet.xsl</stylesheet>
       <name>England Census 1851</name>
       <author>Paul A Golder</author>
       <editdate>3 feb 2013</editdate>
       <type>census</type>
       <country>England</country>
       <period>1851</period>
       <source>ONS image HO 107/1508 </source>
     </template>
     <certificate objecttype="certificate" name="main"   backgroundcolor="#D0F5A9" >
       <stylegroup name="xinput"  borderwidth="1" bordercolor="red" />
       <hgroup   >
         <label layout="MIDDLE" >Page</label>
         <input columns="4" target="pageno" />
         <label layout="RIGHT" >Sequence</label>
         <input columns="4" target="sequenceno"  />
       </hgroup>
       <table name="heading"    >
         <trow>
           <tcell>
             <label>Parish[or Township] of</label>
           </tcell>
           <tcell>
             <label>Ecclesiastical district of</label>
           </tcell>
           <tcell>
             <label>
               <text>City or Borough of</text>
             </label>
           </tcell>
           <tcell>
             <label>Town of</label>
           </tcell>
           <tcell>
             <label>Village of</label>
           </tcell>
         </trow>
         <trow name="headinput" >
           <tcell name="parish" >
             <input  name="parishinput"  target="parish"  />
           </tcell>
           <tcell>
             <input    target="ecclesiasticalDistrict"   />
           </tcell>
           <tcell>
             <input    target="borough"  />
           </tcell>
           <tcell>
             <input    target="town" />
           </tcell>
           <tcell>
             <input    target="village"   />
           </tcell>
         </trow>
       </table>
       <hgroup/>
       <table name="people"  objecttype="people"  borderwidth="1"   >
         <stylegroup name="xtrow"  borderwidth="1" bordercolor="red" />
         <stylegroup name="xinput"  borderwidth="1"  bordercolor="blue" backgroundcolor="silver" />
         <trow  >
           <tcell>
             <label  direction="vertical" fontsize="8" >
               <text>No of</text>
               <text>house-</text>
               <text>holders</text>
               <text>schedule</text>
             </label>
           </tcell>
           <tcell>
             <label>
               <text>Name of Street, Place, or</text>
               <text>Road, and Name or</text>
               <text> No. of House</text>
             </label>
           </tcell>
           <tcell>
             <label>
               <text>Name and Surname of each Person</text>
               <text>who abode in the house</text>
               <text>on the Night of the 30th March, 1851</text>
             </label>
           </tcell>
           <tcell>
             <label>
               <text>Relation</text>
               <text>to</text>
               <text>Head of Family</text>
             </label>
           </tcell>
           <tcell>
             <label>Condition</label>
           </tcell>
           <tcolumn colspan="2" >
             <tcell layout="FILLV" >
               <label >Age of</label>
             </tcell>
             <trow  >
               <tcell>
                 <label fontsize="8" >Males</label>
               </tcell>
               <tcell>
                 <label  fontsize="8" >Females</label>
               </tcell>
             </trow>
           </tcolumn>
           <tcell>
             <label>
               <text>Rank, Profession</text>
               <text>or Occupation</text>
             </label>
           </tcell>
           <tcell>
             <label>Where Born</label>
           </tcell>
           <tcell>
             <label>
               <text>Whether</text>
               <text>Blind or Deaf-</text>
               <text>-and-Dumb</text>
             </label>
           </tcell>
         </trow>
         <trow  rows ="10"  objecttype="person"  >
           <tcell>
             <input    target="householdReference"  />
           </tcell>
           <tcell>
             <input    target="address"  />
           </tcell>
           <tcell>
             <input    target="fullname"  />
           </tcell>
           <tcell>
             <input    target="roleInHousehold"  />
           </tcell>
           <tcell>
             <input    target="maritalStatus"  />
           </tcell>
           <tcell>
             <input  target="age:gender=male"  />
           </tcell>
           <tcell>
             <input  target="age:gender=female"  />
           </tcell>
           <tcell>
             <input    target="occupation"  />
           </tcell>
           <tcell>
             <input    target="birthplace"  />
           </tcell>
           <tcell>
             <input    target="note"  />
           </tcell>
         </trow>
         <trow   >
           <tcell  >
             <label   >Total of Houses  </label>
           </tcell>
           <tcell/>
           <tcell/>
           <tcell/>
           <tcell/>
           <tcell>
             <input  target="totalMales"  />
           </tcell>
           <tcell>
             <input  target="totalFemales"  />
           </tcell>
           <tcell/>
           <tcell/>
         </trow>
       </table>
     </certificate>
   </sourcedocument>
 </sourcedocuments>

=== paulagolder/jcert/Certificates/temp/temp_WestminsterMarriageCert_template.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE sourcedocuments  PUBLIC "-//Paul Golder//DTD jcerttemplate//EN" "http://lerot.org/Templates/jcerttemplate.dtd">

<sourcedocuments>
    <sourcedocument>
        <template>
            <templateID>westminstermarriage</templateID>
            <version>2</version>
            <stylesheet>../Stylesheets/WestminsterMarriageCert_stylesheet.xsl</stylesheet>
            <name>Copy of an entry of marriage St James Westminster</name>
            <savefilepattern>Marriages/Marriage_cert.xml</savefilepattern>
            <author>Paul A Golder</author>
            <editdate>8 feb 2013</editdate>
            <type>Marriage certificate</type>
            <country>England</country>
        </template>
        <certificate  objecttype="certificate" name="main"  backgroundcolor="#CEF6CE" >
            <styleblock name="input"  borderwidth="0"  columns="20" backgroundcolor="#C2C2C2"/>
            <vgroup name="heading"  >
                <hblock name="page"    >
                    <label layout="center"  font-size="20"    >Page</label>
                    <input target="pageNumber"  columns="4" />
                </hblock>
                
                <vgroup  name="title" >
                    <hblock  backgroundcolor="black" height="5" />
                    <hblock  >
                        <label  name="trace" layout="center"  font-size="20"   >MARRIAGES solemnized in the Parish of St. James Westminster</label>
                    </hblock>
                    <hblock>
                        <label layout="center"  font-size="20"  >in the County of Middlesex, in the Year</label>
                        <input   target="year"  font-size="20" columns="4" />
                    </hblock>
                </vgroup>
            </vgroup>
            <hgroup  name="dummy1" backgroundcolor="black" height="5" />
            <hgroup name="dummy2" height="50"  />
            <vgroup   name="marriage"  objecttype="marriage"  >
                <hblock >
                    <input height="20" layout="right"  target="groom.name"   columns="40" />
                    <label>of</label>
                    <input      target="groom.residence"  columns="5" />
                    <label>Parish</label>
                </hblock>
                <hblock  height="20" />
                <hblock>
                    <label>and</label>
                    <input height="10"  layout="right"   target="bride.name"  columns="40" />
                    <label>of</label>
                    <input      target="bride.residence"  columns="5" />
                    <label>Parish</label>
                </hblock>
                <hblock height="10" />
                <hblock>
                    <label>were married in this church by</label>
                    <input     target="banns"  columns="20" />
                    <label>with consent of</label>
                    <input      target="consent"  columns="20" />
                </hblock>
                <hblock height="10" />
                <hblock>
                    <label>this</label>
                    <input      target="day" />
                    <label>Day of</label>
                    <input      target="month" />
                    <label>in the Year One thousand eight hundred and thirty two</label>
                </hblock>
                <hblock height="10" />
                <hblock>
                    <label layout="center" >By me</label>
                    <input width="40"  target="official"  />
                </hblock>
                <hblock height="10" />
                <vgroup  borderwidth="1" bordercolor="blue" >
                    <hblock   >
                        <hblock layout="left" >
                            <label>This marriage was solemized between us</label>
                            <label font-size="40" >{</label>
                        </hblock>
                        <vblock tgap="10">
                            <input      target="groom.name" />
                            <hblock height="5" />
                            <input      target="bride.name" />
                        </vblock>
                    </hblock>
                    <hgroup  >
                        <hblock   layout="right" >
                            <label>in the presence of</label>
                            <label font-size="40" >{</label>
                        </hblock>
                        <vblock layout="FILLW" tgap="10" >
                            <input      target="witness.first" />
                            <hblock height="5" />
                            <input      target="witness.second" />
                        </vblock>
                    </hgroup>
                </vgroup>
            </vgroup>
        </certificate>
    </sourcedocument>
</sourcedocuments>
