=== paulagolder/jcert/Certificates/Dev/jcerttemplate.dtd
<!ELEMENT sourcedocuments (sourcedocument*)>
<!ELEMENT sourcedocument (template, certificate)>
<!ELEMENT template (templateID , version?, stylesheet ,name?, savefilepattern?, author?, editdate?, type?,country?, period?, source?)>

<!ELEMENT templateID ( #PCDATA) >
<!ELEMENT version ( #PCDATA) >
<!ELEMENT savefilepattern ( #PCDATA) >
<!ELEMENT stylesheet ( #PCDATA) >
<!ELEMENT name ( #PCDATA) >
<!ELEMENT author ( #PCDATA) >
<!ELEMENT editdate ( #PCDATA) >
<!ELEMENT type ( #PCDATA) >
<!ELEMENT country ( #PCDATA) >
<!ELEMENT period ( #PCDATA) >
<!ELEMENT source ( #PCDATA) >

<!ELEMENT certificate (styleblock | hgroup | vgroup | table )* >
<!ATTLIST certificate
name NMTOKEN #IMPLIED
layout NMTOKEN #IMPLIED
objecttype CDATA #IMPLIED
backgroundcolor CDATA #IMPLIED
foregroundcolor CDATA #IMPLIED
borderwidth CDATA #IMPLIED
bordercolor CDATA #IMPLIED
height CDATA #IMPLIED
width CDATA #IMPLIED
tgap CDATA #IMPLIED
lgap CDATA #IMPLIED
rgap CDATA #IMPLIED
bgap CDATA #IMPLIED
hgap CDATA #IMPLIED
vgap CDATA #IMPLIED
gaps CDATA #IMPLIED
>

<!ELEMENT styleblock EMPTY >
<!ATTLIST styleblock
name NMTOKEN #IMPLIED
objecttype CDATA #IMPLIED
backgroundcolor CDATA #IMPLIED
foregroundcolor CDATA #IMPLIED
    bordercolor CDATA #IMPLIED
    borderwidth CDATA #IMPLIED
    font-size NMTOKEN #IMPLIED
    font-style CDATA #IMPLIED
    font-name CDATA #IMPLIED
    height CDATA #IMPLIED
    columns CDATA #IMPLIED
    tgap CDATA #IMPLIED
    lgap CDATA #IMPLIED
    rgap CDATA #IMPLIED
    bgap CDATA #IMPLIED
    hgap CDATA #IMPLIED
    vgap CDATA #IMPLIED
    gaps CDATA #IMPLIED >

    <!ELEMENT hgroup (styleblock | vgroup | hgroup | table  | vblock | hblock )* >
    <!ATTLIST hgroup
    name CDATA #IMPLIED
    layout NMTOKEN #IMPLIED
    objecttype CDATA #IMPLIED
    rows CDATA #IMPLIED
    colspan NMTOKEN #IMPLIED
    rowspan NMTOKEN #IMPLIED
    backgroundcolor CDATA #IMPLIED
    foregroundcolor CDATA #IMPLIED
    bordercolor CDATA #IMPLIED
    borderwidth CDATA #IMPLIED
    height CDATA #IMPLIED
    width CDATA #IMPLIED
    tgap CDATA #IMPLIED
    lgap CDATA #IMPLIED
    rgap CDATA #IMPLIED
    bgap CDATA #IMPLIED
    hgap CDATA #IMPLIED
    vgap CDATA #IMPLIED
    gaps CDATA #IMPLIED
    padding CDATA #IMPLIED
    direction CDATA #IMPLIED
    
    >


    <!ELEMENT vgroup (styleblock  | vgroup | hgroup | table | vblock | hblock )* >
    <!ATTLIST vgroup
    name CDATA #IMPLIED
    layout NMTOKEN #IMPLIED
    colspan NMTOKEN #IMPLIED
    rowspan NMTOKEN #IMPLIED
    objecttype CDATA #IMPLIED
    backgroundcolor CDATA #IMPLIED
    foregroundcolor CDATA #IMPLIED
    bordercolor CDATA #IMPLIED
    borderwidth CDATA #IMPLIED
    height CDATA #IMPLIED
    width CDATA #IMPLIED
    tgap CDATA #IMPLIED
    lgap CDATA #IMPLIED
    rgap CDATA #IMPLIED
    bgap CDATA #IMPLIED
    hgap CDATA #IMPLIED
    vgap CDATA #IMPLIED
    gaps CDATA #IMPLIED
    align CDATA #IMPLIED
    padding CDATA #IMPLIED
        >

        

    <!ELEMENT vblock (styleblock  |  vblock | hblock | label | input  )* >
    <!ATTLIST vblock
    name CDATA #IMPLIED
    layout NMTOKEN #IMPLIED
    colspan NMTOKEN #IMPLIED
    rowspan NMTOKEN #IMPLIED
    objecttype CDATA #IMPLIED
    backgroundcolor CDATA #IMPLIED
    foregroundcolor CDATA #IMPLIED
    bordercolor CDATA #IMPLIED
    borderwidth CDATA #IMPLIED
    height CDATA #IMPLIED
    width CDATA #IMPLIED
    tgap CDATA #IMPLIED
    lgap CDATA #IMPLIED
    rgap CDATA #IMPLIED
    bgap CDATA #IMPLIED
    hgap CDATA #IMPLIED
    vgap CDATA #IMPLIED
    gaps CDATA #IMPLIED
    align CDATA #IMPLIED
        >
    
    
    <!ELEMENT hblock (styleblock  |  vblock | hblock | label | input  )* >
    <!ATTLIST hblock
    name CDATA #IMPLIED
     align NMTOKEN #IMPLIED
    layout NMTOKEN #IMPLIED
    colspan NMTOKEN #IMPLIED
    rowspan NMTOKEN #IMPLIED
    objecttype CDATA #IMPLIED
    backgroundcolor CDATA #IMPLIED
    foregroundcolor CDATA #IMPLIED
        bordercolor CDATA #IMPLIED
        borderwidth CDATA #IMPLIED
        height CDATA #IMPLIED
        width CDATA #IMPLIED
        tgap CDATA #IMPLIED
        lgap CDATA #IMPLIED
        rgap CDATA #IMPLIED
        bgap CDATA #IMPLIED
        hgap CDATA #IMPLIED
        vgap CDATA #IMPLIED
        gaps CDATA #IMPLIED
        >

<!ELEMENT table (styleblock | trow )* >
<!ATTLIST table
        name CDATA #IMPLIED
        layout NMTOKEN #IMPLIED
        objecttype CDATA #IMPLIED
        backgroundcolor CDATA #IMPLIED
        foregroundcolor CDATA #IMPLIED
        borderwidth CDATA #IMPLIED
        bordercolor CDATA #IMPLIED
        height CDATA #IMPLIED
        width CDATA #IMPLIED
        tgap CDATA #IMPLIED
        lgap CDATA #IMPLIED
        rgap CDATA #IMPLIED
        bgap CDATA #IMPLIED
        hgap CDATA #IMPLIED
        vgap CDATA #IMPLIED
        gaps CDATA #IMPLIED
>

<!ELEMENT trow (styleblock | tcell | tcolumn )* >
<!ATTLIST trow
        name CDATA #IMPLIED
        layout NMTOKEN #IMPLIED
        objecttype CDATA #IMPLIED
        rows CDATA #IMPLIED
        backgroundcolor CDATA #IMPLIED
        foregroundcolor CDATA #IMPLIED
            borderwidth CDATA #IMPLIED
            bordercolor CDATA #IMPLIED
            height CDATA #IMPLIED
            width CDATA #IMPLIED
            tgap CDATA #IMPLIED
            lgap CDATA #IMPLIED
            rgap CDATA #IMPLIED
            bgap CDATA #IMPLIED
            hgap CDATA #IMPLIED
            vgap CDATA #IMPLIED
            gaps CDATA #IMPLIED
            >

<!ELEMENT tcell (styleblock | hblock| vblock | label | input )* >
<!ATTLIST tcell
            name CDATA #IMPLIED
            layout NMTOKEN #IMPLIED
            objecttype CDATA #IMPLIED
            backgroundcolor CDATA #IMPLIED
            foregroundcolor CDATA #IMPLIED
            borderwidth CDATA #IMPLIED
            bordercolor CDATA #IMPLIED
            height CDATA #IMPLIED
            width CDATA #IMPLIED
            tgap CDATA #IMPLIED
            lgap CDATA #IMPLIED
            rgap CDATA #IMPLIED
            bgap CDATA #IMPLIED
            hgap CDATA #IMPLIED
            vgap CDATA #IMPLIED
            gaps CDATA #IMPLIED
            align NMTOKEN #IMPLIED
            >

<!ELEMENT tcolumn (styleblock | tcell | trow )* >
<!ATTLIST tcolumn
            name CDATA #IMPLIED
            layout NMTOKEN #IMPLIED
            objecttype CDATA #IMPLIED
            backgroundcolor CDATA #IMPLIED
            foregroundcolor CDATA #IMPLIED
                borderwidth CDATA #IMPLIED
                bordercolor CDATA #IMPLIED
                height CDATA #IMPLIED
                width CDATA #IMPLIED
                tgap CDATA #IMPLIED
                lgap CDATA #IMPLIED
                rgap CDATA #IMPLIED
                bgap CDATA #IMPLIED
                hgap CDATA #IMPLIED
                vgap CDATA #IMPLIED
                gaps CDATA #IMPLIED
                >

 
<!ELEMENT input EMPTY >
<!ATTLIST input
                name CDATA #IMPLIED
                target CDATA #REQUIRED
                value  CDATA #IMPLIED
                layout NMTOKEN #IMPLIED
                objecttype CDATA #IMPLIED
                backgroundcolor CDATA #IMPLIED
                foregroundcolor CDATA #IMPLIED
                font-size NMTOKEN #IMPLIED
                font-style CDATA #IMPLIED
                font-name CDATA #IMPLIED
                bordercolor CDATA #IMPLIED
                borderwidth CDATA #IMPLIED
                columns CDATA #IMPLIED
                height CDATA #IMPLIED
                width CDATA #IMPLIED
                tgap CDATA #IMPLIED
                lgap CDATA #IMPLIED
                rgap CDATA #IMPLIED
                bgap CDATA #IMPLIED
                hgap CDATA #IMPLIED
                vgap CDATA #IMPLIED
                gaps CDATA #IMPLIED
                align CDATA #IMPLIED
                >


<!ELEMENT label ( #PCDATA | text )* >
<!ATTLIST label
                name CDATA #IMPLIED
                align NMTOKEN #IMPLIED
                verticalalign NMTOKEN #IMPLIED
                layout NMTOKEN #IMPLIED
                direction CDATA #IMPLIED
                colspan NMTOKEN #IMPLIED
                rowspan NMTOKEN #IMPLIED
                backgroundcolor CDATA #IMPLIED
                foregroundcolor CDATA #IMPLIED
                    borderwidth CDATA #IMPLIED
                    bordercolor CDATA #IMPLIED
                    font-size NMTOKEN #IMPLIED
                    font-style CDATA #IMPLIED
                    font-name CDATA #IMPLIED
                    height CDATA #IMPLIED
                    width CDATA #IMPLIED
                    tgap CDATA #IMPLIED
                    lgap CDATA #IMPLIED
                    rgap CDATA #IMPLIED
                    bgap CDATA #IMPLIED
                    hgap CDATA #IMPLIED
                    vgap CDATA #IMPLIED
                    gaps CDATA #IMPLIED
                    >
                    
 <!ELEMENT text (#PCDATA )>
 <!ATTLIST text
                    font-size NMTOKEN #IMPLIED
                     backgroundcolor CDATA #IMPLIED
 >

=== paulagolder/jcert/Certificates/Dev/LMABirthCertCopy_template.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE sourcedocuments  PUBLIC "-//Paul Golder//DTD jcerttemplate//EN" "http://lerot.org/Templates/jcerttemplate.dtd">


 <sourcedocuments>
   <sourcedocument>
     <template>
       <templateID>LMABirthCopy</templateID>
       <version>3</version>
       <stylesheet>../Stylesheets/LMABirthCopy_stylesheet.xsl</stylesheet>
       <name>LMA Copy of an entry of Birth</name>
       <savefilepattern>Births/birth_cert.xml</savefilepattern>
       <author>Paul A Golder</author>
       <editdate>8-2-2013</editdate>
       <type>Birth certificate</type>
       <country>England</country>
     </template>
     <certificate  name="top"  objecttype ="certificate"  backgroundcolor="#84E96A"    foregroundcolor="#CB410E" >
       <styleblock name="inputcell"  bordercolor="gray"  borderwidth="1"  backgroundcolor="#E4DCDC"  />
       <hgroup bordercolor="black" borderwidth="2" />
       <hgroup name="heading"  >
         <vblock>
           <label >Baptisms solemnized in the Parish of Saint Pancras in the County of Midlesex</label>
           <hblock>
             <label >in the Year One Thousand Eight Hundred and Twenty </label>
             <input target="yeardigit" />
           </hblock>
         </vblock>
       </hgroup>
         <hgroup bordercolor="black" borderwidth="2" />
         <table name="births"    borderwidth="1"   foregroundcolor="black"    >
           <trow borderwidth="0"  >
             <tcell layout="center" >
               <label  layout="top" >
                 <text>When-</text>
                 <text>Baptised</text>
               </label>
             </tcell>
             <tcell>
               <label colspan="2" >Parent Name</label>
               <hblock>
                 <label>
                   <text>Christian</text>
                 </label>
                 <label>
                   <text>Surname</text>
                 </label>
               </hblock>
             </tcell>
             <tcell>
               <label>
                 <text>Abode</text>
               </label>
             </tcell>
             <tcell>
               <label>
                 <text>
                 </text>
                 <text>Quality, Trade or</text>
                 <text>Profession</text>
               </label>
             </tcell>
             <tcell>
               <label>
                 <text>Date of Birth and</text>
                 <text>By whom the ceremony</text>
                 <text>was performed</text>
               </label>
             </tcell>
           </trow>
           <trow   objecttype ="birth"  borderwidth="0" rows="3" >
             <tcell layout="center" >
               <input   target="date" />
               <input   target="entryNo" />
             </tcell>
             <tcell>
               <input     target="name" />
             </tcell>
             <tcell>
               <input     target="fathersForename" />
               <input     target="mothersForename" />
             </tcell>
             <tcell>
               <input     target="surname" />
             </tcell>
             <tcell>
               <input     target="residence" />
             </tcell>
             <tcell>
               <input     target="ocupation" />
             </tcell>
             <tcell>
               <input     target="dateofbirth" />
               <input     target="registrar" />
             </tcell>
           </trow>
         </table>
       </certificate>
     </sourcedocument>
   </sourcedocuments>

=== paulagolder/jcert/Certificates/Dev/EngCensus1871_template.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"  ?>
<!DOCTYPE sourcedocuments  PUBLIC "-//Paul Golder//DTD jcerttemplate//EN" "http://lerot.org/Templates/jcerttemplate.dtd">

<sourcedocuments>
    <sourcedocument>
        <template>
            <templateID>Census1871-0.1</templateID>
            <stylesheet>Stylesheets/EngCensus1871_stylesheet.xsl</stylesheet>
            <name>England Census 1871</name>
            <author>Paul A Golder</author>
            <editdate>16 april 2009</editdate>
            <type>census</type>
            <country>England</country>
            <period>1871</period>
            <source>gro</source>
        </template>
        <certificate  objecttype="certificate" name="main"  backgroundcolor="#D0F5A9" >
            <styleblock name="inputcell"  borderwidth="0"  backgroundcolor="#E4DCDC"  />
            <vgroup borderwidth="1" >
                <hblock>
                    <label >the undermentioned Houses are situate within the Boundaries of the</label>     
                </hblock>
            </vgroup>
            <table name="heading"   >
                <trow>
                    <tcell>
                        <label>Civil Parish[or Township] of</label>
                    </tcell> 
                    <tcell>
                        <label>
                            <text>City or</text>
                            <text>Municipal Borough of</text>
                        </label>
                    </tcell>
                    <tcell>
                        <label>
                            <text>MunicipalWard of</text>
                        </label>
                    </tcell>
                    <tcell>
                        <label>Parliamentary Borough of</label>
                    </tcell>
                    <tcell>
                        <label>Town of</label>
                    </tcell>
                    <tcell>
                        <label>Village or Hamlet of</label>
                    </tcell>
                    <tcell>
                        <label>
                            <text>Local Board or [Improvement</text>
                            <text>Commissioners District] of</text>
                        </label>
                    </tcell>
                    <tcell>
                        <label>Ecclesiastical district of</label>
                    </tcell>
                </trow>
                <trow>
                    <tcell>
                        <input    target="parish"  />
                    </tcell> 
                    <tcell>
                        <input    target="municipalBorough"  />
                    </tcell>
                    <tcell>
                        <input    target="ward"  />
                    </tcell>
                    <tcell>
                        <input    target="parliamentaryBorough" />
                    </tcell>
                    <tcell>
                        <input    target="town"   />
                    </tcell>
                    <tcell>
                        <input    target="hamlet"  />
                    </tcell>
                    <tcell>
                        <input    target="localBoard"  />
                    </tcell>
                    <tcell>
                        <input    target="ecclesiasticalDistrict"   />
                    </tcell>
                </trow>
            </table>
            <hgroup/>
            <table name="people"  objecttype="people" borderwidth="1"  >
                <trow  >
                    <tcell>
                        <label>
                            <text>No of</text>
                            <text>Schedule</text>
                        </label>
                    </tcell>
                    <tcell>
                        <label>
                            <text>ROAD, STREET etc </text>
                            <text>and No or NAME of HOUSE</text>
                        </label>
                    </tcell>
                    <tcell>
                        <label colspan="2" align="center" >Houses </label>
                        <label  width="30" font-size="8">
                            <text>In-</text>
                            <text>habit-</text>
                            <text>ed </text>
                        </label>
                    </tcell>
                    <tcell>
                        <label></label>
                        <label width="30"  font-size="8">
                            <text>unin-</text>
                            <text>habited</text>
                            <text>(U.). or</text>
                            <text>Building</text>
                            <text>(B.).</text>
                        </label>
                    </tcell>
                    <tcell>
                        <label>
                            <text>NAME and Surname of Each</text>
                            <text>Person</text>
                        </label>
                    </tcell>
                    <tcell>
                        <label>
                            <text>RELATION</text>
                            <text>to Head</text>
                            <text>of Family</text>
                        </label>
                    </tcell>
                    <tcell>
                        <label><text>CON-</text>
                            <text>DITION</text>
                        </label>
                    </tcell>
                    <tcell>
                        <label colspan="2">
                            <text>AGE</text>
                            <text>of</text>
                        </label>
                        <label font-size="8" width="20" >Males</label>
                    </tcell>
                    <tcell>
                        <label/>
                        <label  font-size="8"  width="20" >Females</label>
                    </tcell>
                    <tcell>
                        <label>Rank, Profession, or OCCUPATION</label>
                    </tcell>
                    <tcell>
                        <label>WHERE BORN</label>
                    </tcell>
                    <tcell>
                        <label>
                            <text>Whether</text>
                            <text>1. Deaf and Dumb</text>
                            <text>2. Blind </text>
                            <text>3. Imbecile or Idiot </text>
                            <text>4. Lunatic </text>
                        </label>
                    </tcell>
                </trow>
                <trow rows ="25" objecttype="person"  backgroundcolor="#E4DCDC" borderwidth="0" >
                    <tcell>
                        <input    target="householdReference"  />
                    </tcell>
                    <tcell>
                        <input    target="address"  />
                    </tcell>
                    <tcell>
                        <input    target="inhabitedHouse"  />
                    </tcell>
                    <tcell>
                        <input    target="uninhabitedHouse"  />
                    </tcell>
                    <tcell>
                        <input    target="fullname"  />
                    </tcell>
                    <tcell>
                        <input    target="roleInHousehold"  />
                    </tcell>
                    <tcell>
                        <input    target="maritalStatus"  />
                    </tcell>
                    <tcell>
                        <input  target="age:gender=male"  />
                    </tcell>
                    <tcell>
                        <input    target="age:gender=female"  />
                    </tcell>
                    <tcell>
                        <input    target="occupation"  />
                    </tcell>
                    <tcell>
                        <input    target="birthplace"  />
                    </tcell>
                    <tcell>
                        <input    target="note"  />
                    </tcell>
                </trow>
                <trow>
                    <tcell>
                        <label colspan="2">Total of Houses  </label>
                    </tcell>
                    <tcell/>
                    <tcell>
                        <input  target="totalInhabited"  />
                    </tcell>
                    <tcell>
                        <input  target="totalUninhabited"  />
                    </tcell>
                    <tcell>
                        <label colspan="3">Total of Males and Females </label>
                    </tcell>
                    <tcell/>
                    <tcell/>
                    <tcell>
                        <input  target="totalMales"  />
                    </tcell>
                    <tcell>
                        <input  target="totalFemales"  />
                    </tcell>
                    <tcell/>
                    <tcell/>
                    <tcell/>
                </trow>
            </table>
        </certificate>
    </sourcedocument>
</sourcedocuments>

=== paulagolder/jcert/Certificates/temp/temp_EngCensus1881_template.xml.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE sourcedocuments  PUBLIC "-//Paul Golder//DTD jcerttemplate//EN" "http://lerot.org/Templates/jcerttemplate.dtd">


  <sourcedocuments>
    <sourcedocument>
      <templateID>Census1881-0.1</templateID>
      <stylesheet>Stylesheets/EngCensus1881_stylesheet.xsl</stylesheet>
      <name>England Census 1881</name>
      <author>Paul A Golder</author>
      <editdate>16 april 2009</editdate>
      <type>census</type>
      <country>England</country>
      <period>1881</period>
      <source></source>
      <certificate  objecttype="certificate" name="main"   >
        <styleblock name="inputcell"  borderwidth="0"  backgroundcolor="#E4DCDC"  />
        <vgroup >
          <vgroup borderwidth="1" >
            <hblock>
              <label >the undermentioned Houses are situate within the Boundaries of the</label>
            </hblock>
          </vgroup>
          <table name="heading"  rows="1"  >
            <hgroup borderwidth="1" >
              <vblock>
                <label>Civil Parish[or Township] of</label>
              </vblock> 
              <vblock>
                <label>
                  <text>City or</text>
                  <text>Municipal Borough of</text>
                </label>
              </vblock>
              <vblock>
                <label>
                  <text>Municipal Ward of</text>
                </label>
              </vblock>
              <vblock>
                <label>Parliamentary Borough of</label>
              </vblock>
              <vblock>
                <label>
                  <text>Town or Village or</text>
                  <text>Hamlet of</text>
                </label>
              </vblock>
              <vblock>
                <label>
                  <text>Urban Sanitary District of</text>
                </label>
              </vblock>
              <vblock>
                <label>
                  <text>Ruraln Sanitary District of</text>
                </label>
              </vblock>
              <vblock>
                <label>Ecclesiastical district of</label>
              </vblock>
            </hgroup>
            <hgroup>
              <vblock>
                <input    target="parish"  />
              </vblock> 
              <vblock>
                <input    target="municipalBorough"  />
              </vblock>
              <vblock>
                <input    target="ward"  />
              </vblock>
              <vblock>
                <input    target="parliamentaryBorough" />
              </vblock>
              <vblock>
                <input    target="town"   />
              </vblock>
              <vblock>
                <input    target="urbanSanitaryDistrict"  />
              </vblock>
              <vblock>
                <input    target="localBoard"  />
              </vblock>
              <vblock>
                <input    target="ruralSanitaryDistrict"  />
              </vblock>
            </hgroup>
          </table>
          <hgroup/>
          <table name="people" rows ="25" objecttype="people" borderwidth="1"  >
            <hgroup>
              <vblock>
                <label>
                  <text>No of</text>
                  <text>Schedule</text>
                </label>
              </vblock>
              <vblock>
                <label>
                  <text>ROAD, STREET etc </text>
                  <text>and No or NAME of HOUSE</text>
                </label>
              </vblock>
              <vblock>
                <label colspan="2" align="center" >Houses </label>
                <label  width="30" font-size="8">
                  <text>In-</text>
                  <text>habit-</text>
                  <text>ed </text>
                </label>
              </vblock>
              <vblock>
                <label></label>
                <label width="30"  font-size="8">
                  <text>unin-</text>
                  <text>habited</text>
                  <text>(U.). or</text>
                  <text>Building</text>
                  <text>(B.).</text>
                </label>
              </vblock>
              <vblock>
                <label>
                  <text>NAME and Surname of each</text>
                  <text>Person</text>
                </label>
              </vblock>
              <vblock>
                <label>
                  <text>RELATION</text>
                  <text>to</text>
                  <text>Head of Family</text>
                </label>
              </vblock>
              <vblock>
                <label><text>CON-</text>
                  <text>DITION</text>
                  <text>as to</text>
                  <text>Marriage</text>
                </label>
              </vblock>
              <vblock>
                <label colspan="2">
                  <text>AGE last</text>
                  <text>Birthday</text>
                  <text>of</text>
                </label>
                <label font-size="8" width="30" >Males</label>
              </vblock>
              <vblock>
                <label/>
                <label  font-size="8" width="30" >Females</label>
              </vblock>
              <vblock>
                <label>Rank, Profession, or OCCUPATION</label>
              </vblock>
              <vblock>
                <label>WHERE BORN</label>
              </vblock>
              <vblock>
                <label font-size="8">
                  <text>if</text>
                  <text>(1). Deaf and Dumb</text>
                  <text>(2). Blind </text>
                  <text>(3). Imbecile or Idiot </text>
                  <text>(4). Lunatic </text>
                </label>
              </vblock>
            </hgroup>
            <hgroup rows="25" objecttype ="person" >
              <vblock>
                <input    target="householdReference"  />
              </vblock>
              <vblock>
                <input    target="address"  />
              </vblock>
              <vblock>
                <input    target="inhabitedHouse"  />
              </vblock>
              <vblock>
                <input    target="uninhabitedHouse"  />
              </vblock>
              <vblock>
                <input    target="fullname"  />
              </vblock>
              <vblock>
                <input    target="roleInHousehold"  />
              </vblock>
              <vblock>
                <input    target="maritalStatus"  />
              </vblock>
              <vblock>
                <input    target="age:gender=male"  />
              </vblock>
              <vblock>
                <input    target="age:gender=female"  />
              </vblock>
              <vblock>
                <input    target="occupation"  />
              </vblock>
              <vblock>
                <input    target="birthplace"  />
              </vblock>
              <vblock>
                <input    target="note"  />
              </vblock>
            </hgroup>
            <hgroup>
              <vblock>
                <label colspan="2">Total of Houses  </label>
              </vblock>
              <vblock />
              <vblock>
                <input  target="totalInhabited"  />
              </vblock>
              <vblock>
                <input  target="totalUninhabited"  />
              </vblock>
              <vblock>
                <label colspan="3">Total of Males and Females </label>
              </vblock>
              <vblock />
              <vblock />
              <vblock>
                <input  target="totalMales"  />
              </vblock>
              <vblock>
                <input  target="totalFemales"  />
              </vblock>
              <vblock />
              <vblock />
              <vblock />
            </hgroup>
          </table>
        </vgroup>
      </certificate>
    </sourcedocument>
  </sourcedocuments>
