=== paulagolder/jcert/Certificates/Dev/jcerttemplate.dtd
<!ELEMENT sourcedocuments (sourcedocument*)>
<!ELEMENT sourcedocument (template, certificate)>
<!ELEMENT template (templateID , version?, stylesheet ,name?, savefilepattern?, author?, editdate?, type?,country?, period?, source?)>

<!ELEMENT templateID ( #PCDATA) >
<!ELEMENT version ( #PCDATA) >
<!ELEMENT savefilepattern ( #PCDATA) >
<!ELEMENT stylesheet ( #PCDATA) >
<!ELEMENT name ( #PCDATA) >
<!ELEMENT author ( #PCDATA) >
<!ELEMENT editdate ( #PCDATA) >
<!ELEMENT type ( #PCDATA) >
<!ELEMENT country ( #PCDATA) >
<!ELEMENT period ( #PCDATA) >
<!ELEMENT source ( #PCDATA) >

<!ELEMENT certificate (styleblock | hgroup | vgroup | table )* >
<!ATTLIST certificate
name NMTOKEN #IMPLIED
layout NMTOKEN #IMPLIED
objecttype CDATA #IMPLIED
backgroundcolor CDATA #IMPLIED
foregroundcolor CDATA #IMPLIED
borderwidth CDATA #IMPLIED
bordercolor CDATA #IMPLIED
height CDATA #IMPLIED
width CDATA #IMPLIED
tgap CDATA #IMPLIED
lgap CDATA #IMPLIED
rgap CDATA #IMPLIED
bgap CDATA #IMPLIED
hgap CDATA #IMPLIED
vgap CDATA #IMPLIED
gaps CDATA #IMPLIED
>

<!ELEMENT styleblock EMPTY >
<!ATTLIST styleblock
name NMTOKEN #IMPLIED
objecttype CDATA #IMPLIED
backgroundcolor CDATA #IMPLIED
foregroundcolor CDATA #IMPLIED
    bordercolor CDATA #IMPLIED
    borderwidth CDATA #IMPLIED
    font-size NMTOKEN #IMPLIED
    font-style CDATA #IMPLIED
    font-name CDATA #IMPLIED
    height CDATA #IMPLIED
    columns CDATA #IMPLIED
    tgap CDATA #IMPLIED
    lgap CDATA #IMPLIED
    rgap CDATA #IMPLIED
    bgap CDATA #IMPLIED
    hgap CDATA #IMPLIED
    vgap CDATA #IMPLIED
    gaps CDATA #IMPLIED >

    <!ELEMENT hgroup (styleblock | vgroup | hgroup | table  | vblock | hblock )* >
    <!ATTLIST hgroup
    name CDATA #IMPLIED
    layout NMTOKEN #IMPLIED
    objecttype CDATA #IMPLIED
    rows CDATA #IMPLIED
    colspan NMTOKEN #IMPLIED
    rowspan NMTOKEN #IMPLIED
    backgroundcolor CDATA #IMPLIED
    foregroundcolor CDATA #IMPLIED
    bordercolor CDATA #IMPLIED
    borderwidth CDATA #IMPLIED
    height CDATA #IMPLIED
    width CDATA #IMPLIED
    tgap CDATA #IMPLIED
    lgap CDATA #IMPLIED
    rgap CDATA #IMPLIED
    bgap CDATA #IMPLIED
    hgap CDATA #IMPLIED
    vgap CDATA #IMPLIED
    gaps CDATA #IMPLIED
    padding CDATA #IMPLIED
    direction CDATA #IMPLIED
    
    >


    <!ELEMENT vgroup (styleblock  | vgroup | hgroup | table | vblock | hblock )* >
    <!ATTLIST vgroup
    name CDATA #IMPLIED
    layout NMTOKEN #IMPLIED
    colspan NMTOKEN #IMPLIED
    rowspan NMTOKEN #IMPLIED
    objecttype CDATA #IMPLIED
    backgroundcolor CDATA #IMPLIED
    foregroundcolor CDATA #IMPLIED
    bordercolor CDATA #IMPLIED
    borderwidth CDATA #IMPLIED
    height CDATA #IMPLIED
    width CDATA #IMPLIED
    tgap CDATA #IMPLIED
    lgap CDATA #IMPLIED
    rgap CDATA #IMPLIED
    bgap CDATA #IMPLIED
    hgap CDATA #IMPLIED
    vgap CDATA #IMPLIED
    gaps CDATA #IMPLIED
    align CDATA #IMPLIED
    padding CDATA #IMPLIED
        >

        

    <!ELEMENT vblock (styleblock  |  vblock | hblock | label | input  )* >
    <!ATTLIST vblock
    name CDATA #IMPLIED
    layout NMTOKEN #IMPLIED
    colspan NMTOKEN #IMPLIED
    rowspan NMTOKEN #IMPLIED
    objecttype CDATA #IMPLIED
    backgroundcolor CDATA #IMPLIED
    foregroundcolor CDATA #IMPLIED
    bordercolor CDATA #IMPLIED
    borderwidth CDATA #IMPLIED
    height CDATA #IMPLIED
    width CDATA #IMPLIED
    tgap CDATA #IMPLIED
    lgap CDATA #IMPLIED
    rgap CDATA #IMPLIED
    bgap CDATA #IMPLIED
    hgap CDATA #IMPLIED
    vgap CDATA #IMPLIED
    gaps CDATA #IMPLIED
    align CDATA #IMPLIED
        >
    
    
    <!ELEMENT hblock (styleblock  |  vblock | hblock | label | input  )* >
    <!ATTLIST hblock
    name CDATA #IMPLIED
     align NMTOKEN #IMPLIED
    layout NMTOKEN #IMPLIED
    colspan NMTOKEN #IMPLIED
    rowspan NMTOKEN #IMPLIED
    objecttype CDATA #IMPLIED
    backgroundcolor CDATA #IMPLIED
    foregroundcolor CDATA #IMPLIED
        bordercolor CDATA #IMPLIED
        borderwidth CDATA #IMPLIED
        height CDATA #IMPLIED
        width CDATA #IMPLIED
        tgap CDATA #IMPLIED
        lgap CDATA #IMPLIED
        rgap CDATA #IMPLIED
        bgap CDATA #IMPLIED
        hgap CDATA #IMPLIED
        vgap CDATA #IMPLIED
        gaps CDATA #IMPLIED
        >

<!ELEMENT table (styleblock | trow )* >
<!ATTLIST table
        name CDATA #IMPLIED
        layout NMTOKEN #IMPLIED
        objecttype CDATA #IMPLIED
        backgroundcolor CDATA #IMPLIED
        foregroundcolor CDATA #IMPLIED
        borderwidth CDATA #IMPLIED
        bordercolor CDATA #IMPLIED
        height CDATA #IMPLIED
        width CDATA #IMPLIED
        tgap CDATA #IMPLIED
        lgap CDATA #IMPLIED
        rgap CDATA #IMPLIED
        bgap CDATA #IMPLIED
        hgap CDATA #IMPLIED
        vgap CDATA #IMPLIED
        gaps CDATA #IMPLIED
>

<!ELEMENT trow (styleblock | tcell | tcolumn )* >
<!ATTLIST trow
        name CDATA #IMPLIED
        layout NMTOKEN #IMPLIED
        objecttype CDATA #IMPLIED
        rows CDATA #IMPLIED
        backgroundcolor CDATA #IMPLIED
        foregroundcolor CDATA #IMPLIED
            borderwidth CDATA #IMPLIED
            bordercolor CDATA #IMPLIED
            height CDATA #IMPLIED
            width CDATA #IMPLIED
            tgap CDATA #IMPLIED
            lgap CDATA #IMPLIED
            rgap CDATA #IMPLIED
            bgap CDATA #IMPLIED
            hgap CDATA #IMPLIED
            vgap CDATA #IMPLIED
            gaps CDATA #IMPLIED
            >

<!ELEMENT tcell (styleblock | hblock| vblock | label | input )* >
<!ATTLIST tcell
            name CDATA #IMPLIED
            layout NMTOKEN #IMPLIED
            objecttype CDATA #IMPLIED
            backgroundcolor CDATA #IMPLIED
            foregroundcolor CDATA #IMPLIED
            borderwidth CDATA #IMPLIED
            bordercolor CDATA #IMPLIED
            height CDATA #IMPLIED
            width CDATA #IMPLIED
            tgap CDATA #IMPLIED
            lgap CDATA #IMPLIED
            rgap CDATA #IMPLIED
            bgap CDATA #IMPLIED
            hgap CDATA #IMPLIED
            vgap CDATA #IMPLIED
            gaps CDATA #IMPLIED
            align NMTOKEN #IMPLIED
            >

<!ELEMENT tcolumn (styleblock | tcell | trow )* >
<!ATTLIST tcolumn
            name CDATA #IMPLIED
            layout NMTOKEN #IMPLIED
            objecttype CDATA #IMPLIED
            backgroundcolor CDATA #IMPLIED
            foregroundcolor CDATA #IMPLIED
                borderwidth CDATA #IMPLIED
                bordercolor CDATA #IMPLIED
                height CDATA #IMPLIED
                width CDATA #IMPLIED
                tgap CDATA #IMPLIED
                lgap CDATA #IMPLIED
                rgap CDATA #IMPLIED
                bgap CDATA #IMPLIED
                hgap CDATA #IMPLIED
                vgap CDATA #IMPLIED
                gaps CDATA #IMPLIED
                >

 
<!ELEMENT input EMPTY >
<!ATTLIST input
                name CDATA #IMPLIED
                target CDATA #REQUIRED
                value  CDATA #IMPLIED
                layout NMTOKEN #IMPLIED
                objecttype CDATA #IMPLIED
                backgroundcolor CDATA #IMPLIED
                foregroundcolor CDATA #IMPLIED
                font-size NMTOKEN #IMPLIED
                font-style CDATA #IMPLIED
                font-name CDATA #IMPLIED
                bordercolor CDATA #IMPLIED
                borderwidth CDATA #IMPLIED
                columns CDATA #IMPLIED
                height CDATA #IMPLIED
                width CDATA #IMPLIED
                tgap CDATA #IMPLIED
                lgap CDATA #IMPLIED
                rgap CDATA #IMPLIED
                bgap CDATA #IMPLIED
                hgap CDATA #IMPLIED
                vgap CDATA #IMPLIED
                gaps CDATA #IMPLIED
                align CDATA #IMPLIED
                >


<!ELEMENT label ( #PCDATA | text )* >
<!ATTLIST label
                name CDATA #IMPLIED
                align NMTOKEN #IMPLIED
                verticalalign NMTOKEN #IMPLIED
                layout NMTOKEN #IMPLIED
                direction CDATA #IMPLIED
                colspan NMTOKEN #IMPLIED
                rowspan NMTOKEN #IMPLIED
                backgroundcolor CDATA #IMPLIED
                foregroundcolor CDATA #IMPLIED
                    borderwidth CDATA #IMPLIED
                    bordercolor CDATA #IMPLIED
                    font-size NMTOKEN #IMPLIED
                    font-style CDATA #IMPLIED
                    font-name CDATA #IMPLIED
                    height CDATA #IMPLIED
                    width CDATA #IMPLIED
                    tgap CDATA #IMPLIED
                    lgap CDATA #IMPLIED
                    rgap CDATA #IMPLIED
                    bgap CDATA #IMPLIED
                    hgap CDATA #IMPLIED
                    vgap CDATA #IMPLIED
                    gaps CDATA #IMPLIED
                    >
                    
 <!ELEMENT text (#PCDATA )>
 <!ATTLIST text
                    font-size NMTOKEN #IMPLIED
                     backgroundcolor CDATA #IMPLIED
 >

=== paulagolder/jcert/Certificates/temp/temp_EngCensus1861_template.xml.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE sourcedocuments  PUBLIC "-//Paul Golder//DTD jcerttemplate//EN" "http://lerot.org/Templates/jcerttemplate.dtd">


  <sourcedocuments>
    <sourcedocument>
      <templateID>Census1861-0.1</templateID>
      <stylesheet>Stylesheets/EngCensus1861_stylesheet.xsl</stylesheet>
      <name>England Census 1861</name>
      <author>Paul A Golder</author>
      <editdate>25 march 2009</editdate>
      <type>census</type>
      <country>England</country>
      <period>1861</period>
      <source>Eng.-SheetD.</source>
      <certificate objecttype="certificate"   backgroundcolor="#D0F5A9"  >
        <styleblock name="inputcell"  borderwidth="0"  backgroundcolor="#E4DCDC"  />
        <hgroup />
        <vgroup    >
          <vgroup borderwidth="0" >
            <hblock align="center">
              <label  align="center">the undermentioned Houses are situte within the Boundaries of the</label>
            </hblock>
          </vgroup>
          <table name="heading"   >
            <hgroup>
              <vblock>
                <label>Parish[or Township] of</label>
              </vblock> 
              <vblock>
                <label>
                  <text>City or</text>
                  <text>Municipal Ward of</text>
                </label>
              </vblock>
              <vblock>
                <label>Parliamentary Borough of</label>
              </vblock>
              <vblock>
                <label>Town of</label>
              </vblock>
              <vblock>
                <label>Hamlet or Tything of</label> />
            </vblock>
            <vblock>
              <label>Ecclesiastical district of</label>
            </vblock>
          </hgroup>
          <hgroup>
            <vblock>
              <input    target="parish"  />
            </vblock> 
            <vblock>
              <input    target="ward"  />
            </vblock>
            <vblock>
              <input    target="borough" />
            </vblock>
            <vblock>
              <input    target="town"   />
            </vblock>
            <vblock>
              <input    target="hamlet"  />
            </vblock>
            <vblock>
              <input    target="ecclesiasticalDistrict"   />
            </vblock>
          </hgroup>
        </table>
        <hblock/>
        <table  objecttype="people"  borderwidth="1"  >
          <hgroup   backgroundcolor="blue">
            <vblock>
              <label>
                <text>No of</text>
                <text>Schedule</text>
              </label>
            </vblock>
            <vblock >
              <label backgroundcolor="red" >
                <text backgroundcolor="red" >Road Street etc </text>
                <text>and No or Name </text>
                <text>of House</text>
              </label>
            </vblock>
            <vblock>
              <label colspan="2" align="center" >Houses </label>
              <label   font-size="8">
                <text>In-</text>
                <text>habited </text>
              </label>
            </vblock>
            <vblock>
              <label></label>
              <label  font-size="8">
                <text>unin-</text>
                <text>habited</text>
                <text>(U.). or</text>
                <text>Building</text>
                <text>(B.).</text>
              </label>
            </vblock>
            <vblock>
              <label>
                <text>Name and Surname of Each</text>
                <text>Person</text>
              </label>
            </vblock>
            <vblock>
              <label>
                <text>Relation</text>
                <text>to Head</text>
                <text>of Family</text>
              </label>
            </vblock>
            <vblock>
              <label>Condition</label>
            </vblock>
            
            <vblock>
              <label colspan="2">Age of</label>
              <label font-size="8" >Males</label>
            </vblock>
            <vblock>
              <label/>
              <label  font-size="8" >Females</label>
            </vblock>
            <vblock>
              <label>Rank, Profession, or Occupation</label>
            </vblock>
            <vblock>
              <label>Where Born</label>
            </vblock>
            <vblock>
              <label>
                <text>Whether</text>
                <text>Blind or Deaf-</text>
                <text>-and-Dumb</text>
              </label>
            </vblock>
          </hgroup>
          <hgroup   objecttype="person"  rows ="20"  backgroundcolor="#E4DCDC" borderwidth="0" >
            <vblock  >
              <input    target="householdReference"  />
            </vblock>
            <vblock>
              <input    target="address"  />
            </vblock>
            <vblock>
              <input    target="inhabitedHouse"  />
            </vblock>
            <vblock>
              <input    target="uninhabitedHouse"  />
            </vblock>
            <vblock>
              <input    target="fullname"  />
            </vblock>
            <vblock>
              <input    target="roleInHousehold"  />
            </vblock>
            <vblock>
              <input    target="maritalStatus"  />
            </vblock>
            
            <vblock>
              <input  target="age:gender=male"  />
            </vblock>
            <vblock>
              <input    target="age:gender=female"  />
            </vblock>
            <vblock>
              <input    target="occupation"  />
            </vblock>
            <vblock>
              <input    target="birthplace"  />
            </vblock>
            <vblock>
              <input    target="note"  />
            </vblock>
          </hgroup>
          <hgroup>
            <vblock>
              <label colspan="2">Total of Houses  </label>
            </vblock>
            <vblock></vblock>
            <vblock>
              <input  target="totalInhabited"  />
            </vblock>
            <vblock>
              <input  target="totalUninhabited"  />
            </vblock>
            <vblock>
              <label colspan="3">Total of Males and Females </label>
            </vblock>
            <vblock></vblock>
            <vblock></vblock>
            <vblock>
              <input  target="totalMales"  />
            </vblock>
            <vblock>
              <input  target="totalFemales"  />
            </vblock>
            <vblock></vblock>
            <vblock></vblock>
            <vblock></vblock>
          </hgroup>
        </table>
      </vgroup>
    </certificate>
  </sourcedocument>
</sourcedocuments>

=== paulagolder/jcert/Certificates/temp/temp_LMABaptism_template.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE sourcedocuments  PUBLIC "-//Paul Golder//DTD jcerttemplate//EN" "http://lerot.org/Templates/jcerttemplate.dtd">

<sourcedocuments>
    <sourcedocument>
        <template>
            <templateID>LMABaptism</templateID>
            <version>3</version>
            <stylesheet>../Stylesheets/LMABirthCopy_stylesheet.xsl</stylesheet>
            <name>LMA Baptism register</name>
            <savefilepattern>Births/birth_cert.xml</savefilepattern>
            <author>Paul A Golder</author>
            <editdate>8-2-2013</editdate>
            <type>Baptism </type>
            <country>England</country>
        </template>
        <certificate  name="top"  objecttype ="certificate"  backgroundcolor="#84E96A"    foregroundcolor="#CB410E" >
            <styleblock name="input"  bordercolor="gray"  borderwidth="1"  backgroundcolor="#E4DCDC"  />
            <styleblock name="label"   font-size="18"  />
            <hgroup>
            <hblock>
                <label layout="center"  >[Page </label>
                <input target="pageno" columns="4" />
                <label   >]</label>
            </hblock>
        </hgroup>
            <hgroup bordercolor="black" borderwidth="0" height="10" backgroundcolor="black" />
            <vgroup>
                <hblock layout="FILLW"  >
                    <label layout="center"  >Baptisms solemnized in the Parish of Saint Pancras, in the County of Middlesex</label>
                </hblock>
                <hblock>
                    <label layout="center"  >in the Year One Thousand Eight Hundred and Twenty </label>
                    <input  font-size="18" target="yeardigit" columns="10" />
                </hblock>
            </vgroup>
            
            <hgroup bordercolor="black" borderwidth="0"  backgroundcolor="black"  height="5" />
            <table name="births"    borderwidth="1"   foregroundcolor="black"  tgap="4"  >
                <styleblock name="label"  bordercolor="gray"  borderwidth="1" font-size="13"  />
                <styleblock name="input"  height="25" font-size="13"  />
                
                <trow borderwidth="0"  >
                    <tcell >
                        <label   >
                            <text>When-</text>
                            <text>Baptised</text>
                        </label>
                    </tcell>
                    <tcell >
                        <label   >
                            <text>Child's</text>
                            <text>Christian Name.</text>
                        </label>
                    </tcell>
                    <tcolumn>
                        <tcell layout="FILLV" >
                            <label>Parent Name</label>
                        </tcell>
                        <trow layout="BOTTOM" >
                            <tcell>
                                <label>
                                    <text>Christian</text>
                                </label>
                            </tcell>
                            <tcell>
                                <label>
                                    <text>Surname</text>
                                </label>
                            </tcell>
                        </trow>
                    </tcolumn>
                    <tcell>
                        <label>
                            <text>Abode</text>
                        </label>
                    </tcell>
                    <tcell>
                        <label>
                            <text>
                            </text>
                            <text>Quality, Trade or</text>
                            <text>Profession</text>
                        </label>
                    </tcell>
                    <tcell>
                        <label>
                            <text>Date of Birth and</text>
                            <text>By whom the ceremony</text>
                            <text>was performed</text>
                        </label>
                    </tcell>
                </trow>
                <trow   objecttype ="birth"  borderwidth="0" rows="3" >
                    <tcell layout="center" >
                        <input   target="date"   />
                        <input   target="entryNo" />
                    </tcell>
                    <tcell>
                        <input     target="name" />
                    </tcell>
                    <tcell>
                        <input     target="fathersForename" />
                        <input     target="mothersForename" />
                    </tcell>
                    <tcell>
                        <input     target="surname" />
                    </tcell>
                    <tcell>
                        <input     target="residence" />
                    </tcell>
                    <tcell>
                        <input     target="ocupation" />
                    </tcell>
                    <tcell>
                        <input     target="dateofbirth" />
                        <input     target="registrar" />
                    </tcell>
                </trow>
            </table>
        </certificate>
    </sourcedocument>
</sourcedocuments>

=== paulagolder/jcert/Certificates/temp/temp_xEngCensus1841_template.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE sourcedocuments  PUBLIC "-//Paul Golder//DTD jcerttemplate//EN" "http://lerot.org/Templates/jcerttemplate.dtd">

 <sourcedocuments>
   <sourcedocument>
     <template>
       <templateID>Census1841</templateID>
       <version>2</version>
       <stylesheet>../Stylesheets/EngCensus1841_stylesheet.xsl</stylesheet>
       <name>England Census 1841</name>
       <author>Paul A Golder</author>
       <editdate>11 Feb 2013</editdate>
       <type>census</type>
       <country>England</country>
       <period>1841</period>
       <source>ONS images</source>
     </template>
     <certificate  objecttype="certificate" backgroundcolor="#D0F5A9"  >
       
       <vgroup    >
         <hgroup   >
           <label layout="MIDDLE" >Page</label>
           <input columns="4" target="pageno" />
           <label layout="RIGHT" >Sequence</label>
           <input columns="4" target="sequenceno"  />
         </hgroup>
         <hgroup   >
           <vgroup   >
             <hgroup name="bor" >
               <label name = "boro" >City or Borough of</label>
               <input columns="20" target="borough"   />
             </hgroup>
             <hgroup   name="par"  >
               <label  >Parish or Township of</label>
               <input columns="20" target="parish"   />
             </hgroup>
           </vgroup>
           <vgroup   layout="RIGHT" >
             <hgroup   >
               <label fontsize="12"  >Enumeration Schedule</label>
             </hgroup>
           </vgroup>
         </hgroup>
       </vgroup>
       <hgroup name ="filler"  height="30"   />
       <table  objecttype="people" borderwidth="1"  >
         <trow>
           <tcell>
             <label>Place</label>
           </tcell>
           <tcolumn   colspan="2" >
             <tcell layout="FILLV"   >
               <label >HOUSES </label>
             </tcell>
             <trow>
               <tcell>
                 <label name="houses"  direction="vertical" fontsize="8">
                   <text>Uninhabited</text>
                   <text>or Building</text>
                 </label>
               </tcell>
               <tcell>
                 <label fontsize="8" direction="vertical">Inhabited</label>
               </tcell>
             </trow>
           </tcolumn>
           <tcell>
             <label  >
               <text>NAMES</text>
               <text fontsize="8">of each Person who obode therein </text>
               <text fontsize="8">the preceding night</text>
             </label>
           </tcell>
           <tcolumn   colspan="2"  >
             <tcell >
               <label align="center"  >
                 <text>AGE </text>
                 <text>and </text>
                 <text>SEX</text>
               </label>
             </tcell>
             <trow  name="sex" layout="FILLV"  >
               <tcell >
                 <label name="males" fontsize="8" direction="vertical" >Males</label>
               </tcell>
               <tcell  >
                 <label fontsize="8" direction="vertical">Females</label>
               </tcell>
             </trow>
           </tcolumn>

           <tcell>
             <label>
               <text>PROFESSION, TRADE</text>
               <text>EMPLOYMENT</text>
               <text>or of</text>
               <text>INDEPENDENT MEANS</text>
             </label>
           </tcell>
           <tcolumn   colspan="2" >
             <tcell>
               <label >Where born</label>
             </tcell>
             <trow>
               <tcell>
                 <label fontsize="8" direction="vertical">
                   <text>Whether born</text>
                   <text>in same County</text>
                 </label>
               </tcell>
               <tcell>
                 <label fontsize="8" direction="vertical">
                   <text>Whether born in</text>
                   <text>England Ireland </text>
                   <text>or Foriegn Parts</text>
                 </label>
               </tcell>
             </trow>
           </tcolumn>
         </trow>
         <trow objecttype="person" rows="10" borderwidth="0" >
           <tcell>
             <input target="place"   />
           </tcell>
           <tcell>
             <input target="uninhabitedHouse"   />
           </tcell>
           <tcell>
             <input target="inhabitedHouse"   />
           </tcell>
           <tcell>
             <input target="name"   />
           </tcell>
           <tcell>
             <input target="age:gender=male"  width="10" />
           </tcell>
           <tcell>
             <input target="age:gender=female"   />
           </tcell>
           <tcell>
             <input target="occupation"   />
           </tcell>
           <tcell>
             <input target="birthplaceThisCounty"   />
           </tcell>
           <tcell>
             <input target="birthplaceOther"   />
           </tcell>
         </trow>
         <trow>
           <tcell>
             <label>Total in Page</label>
           </tcell>
           <tcell>
             <input target="totalUninhabitedHouses"   />
           </tcell>
           <tcell>
             <input target="totalInhabitedHouses"   />
           </tcell>
           <tcell>
           </tcell>
           <tcell>
             <input target="totalMales"   />
           </tcell>
           <tcell>
             <input target="totalFemales"   />
           </tcell>
           <tcell>
           </tcell>
           <tcell>
             <input target="totalThisCounty"   />
           </tcell>
           <tcell>
             <input target="totalOther"   />
           </tcell>
         </trow>
       </table>
     </certificate>
   </sourcedocument>
 </sourcedocuments>
