=== paulagolder/jcert/Certificates/Templates/jcerttemplate.dtd
<!ELEMENT sourcedocuments (sourcedocument*)>
<!ELEMENT sourcedocument (templateID , stylesheet ,name?, savefilepattern?, author?, editdate?, type?,country?, period?, source?, certificate)>
<!ELEMENT templateID ( #PCDATA) >
<!ELEMENT savefilepattern ( #PCDATA) >
<!ELEMENT stylesheet ( #PCDATA) >
<!ELEMENT name ( #PCDATA) >
<!ELEMENT author ( #PCDATA) >
<!ELEMENT editdate ( #PCDATA) >
<!ELEMENT type ( #PCDATA) >
<!ELEMENT country ( #PCDATA) >
<!ELEMENT period ( #PCDATA) >
<!ELEMENT source ( #PCDATA) >

<!ELEMENT certificate (styleblock | hgroup | vgroup | table )* >
     <!ATTLIST certificate name NMTOKEN #IMPLIED >
     <!ATTLIST certificate objecttype NMTOKEN #IMPLIED   >

      <!ELEMENT styleblock EMPTY >
         <!ATTLIST styleblock
             name NMTOKEN #IMPLIED   
             objecttype NMTOKEN #IMPLIED   
             backgroundcolor CDATA #IMPLIED   
             foregroundcolor CDATA #IMPLIED   
             borderwidth CDATA #IMPLIED    >

      <!ELEMENT hgroup (stylegroup | vgroup | hgroup | hblock | vblock | table )* >
          <!ATTLIST hgroup
             name NMTOKEN #IMPLIED   
             objecttype NMTOKEN #IMPLIED   
             backgroundcolor CDATA #IMPLIED   
             foregroundcolor CDATA #IMPLIED   
             borderwidth CDATA #IMPLIED    >


      <!ELEMENT vgroup (stylegroup  | vgroup | hgroup | hblock | vblock | table )* >
          <!ATTLIST vgroup 
             name NMTOKEN #IMPLIED   
             objecttype NMTOKEN #IMPLIED   
             backgroundcolor CDATA #IMPLIED   
             foregroundcolor CDATA #IMPLIED   
             borderwidth CDATA #IMPLIED    >


      <!ELEMENT table (stylegroup | hgroup )* >
          <!ATTLIST table 
             name NMTOKEN #IMPLIED   
             objecttype NMTOKEN #IMPLIED   
             backgroundcolor CDATA #IMPLIED   
             foregroundcolor CDATA #IMPLIED   
             borderwidth CDATA #IMPLIED    >


      <!ELEMENT vblock ( input | label | vblock | hblock )* >
          <!ATTLIST vblock 
             name NMTOKEN #IMPLIED   
             objecttype NMTOKEN #IMPLIED   
             backgroundcolor CDATA #IMPLIED   
             foregroundcolor CDATA #IMPLIED   
             borderwidth CDATA #IMPLIED    >


      <!ELEMENT hblock ( input | label | vblock | hblock )* >
          <!ATTLIST hblock 
             name NMTOKEN #IMPLIED   
             objecttype NMTOKEN #IMPLIED   
             backgroundcolor CDATA #IMPLIED   
             foregroundcolor CDATA #IMPLIED   
             borderwidth CDATA #IMPLIED    >


      <!ELEMENT input EMPTY >
          <!ATTLIST input target CDATA #REQUIRED >

      <!ELEMENT label ( #PCDATA | text )* >
         <!ATTLIST label
             align NMTOKEN #IMPLIED  
             colspan NMTOKEN #IMPLIED  
             rowspan NMTOKEN #IMPLIED  
             font-size NMTOKEN #IMPLIED  
             height NMTOKEN #IMPLIED   >
             
      <!ELEMENT text (#PCDATA ) >

=== paulagolder/jcert/Certificates/Templates/EngCensus1851_template.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE sourcedocuments  PUBLIC "-//Paul Golder//DTD jcerttemplate//EN" "http://lerot.org/Templates/jcerttemplate.dtd">


  <sourcedocuments>
    <sourcedocument>
      <templateID>Census1851-0.1</templateID>
      <stylesheet>Stylesheets/EngCensus1851_stylesheet.xsl</stylesheet>
      <name>England Census 1851</name>
      <author>Paul A Golder</author>
      <editdate>16 April 2009</editdate>
      <type>census</type>
      <country>England</country>
      <period>1851</period>
      <source>Df.</source>
      <certificate objecttype="certificate" name="main"   backgroundcolor="#D0F5A9" >
        <styleblock name="inputcell"  borderwidth="0"  backgroundcolor="#E4DCDC"  />
        <table name="heading"  rows="1"  >
          <hgroup>
            <vblock>
              <label>Parish[or Township] of</label>
            </vblock> 
            <vblock>
              <label>Ecclesiastical district of</label>>
            </vblock>
            <vblock>
              <label>
                <text>City or Borough of</text>
              </label>
            </vblock>
            <vblock>
              <label>Town of</label>
            </vblock>
            <vblock>
              <label>Village of</label>
            </vblock>  
          </hgroup>
          <hgroup>
            <vblock>
              <input    target="parish"  />
            </vblock> 
            <vblock>
              <input    target="ecclesiasticalDistrict"   />
            </vblock>
            <vblock>
              <input    target="borough"  />
            </vblock>
            <vblock>
              <input    target="town" />
            </vblock>
            <vblock>
              <input    target="village"   />
            </vblock>  
          </hgroup>
        </table>
        <hgroup/>
        <table name="people"  objecttype="people"  borderwidth="1"   >
          <hgroup>
            <vblock>
              <label  direction="vertical" font-size="8" >
                <text>No of</text>
                <text>house-</text>
                <text>holders</text>
                <text>schedule</text>
              </label>
            </vblock>
            <vblock>
              <label>
                <text>Name of Street, Place, or</text>
                <text>Road, and Name or</text>
                <text> No. of House</text>
              </label>
            </vblock>
            <vblock>
              <label>
                <text>Name and Surname of each Person</text>
                <text>who abode in the house</text>
                <text>on the Night of the 30th March, 1851</text>
              </label>
            </vblock>
            <vblock>
              <label>
                <text>Relation</text>
                <text>to</text>
                <text>Head of Family</text>
              </label>
            </vblock>
            <vblock>
              <label>Condition</label>
            </vblock>
            <vblock>
              <label colspan="2">Age of</label>
              <label font-size="8" >Males</label>
            </vblock>
            <vblock>
              <label  />
              <label  font-size="8" >Females</label>
            </vblock>
            <vblock>
              <label>
                <text>Rank, Profession</text>
                <text>or Occupation</text>
              </label>
            </vblock>
            <vblock>
              <label>Where Born</label>
            </vblock>
            <vblock>
              <label>
                <text>Whether</text>
                <text>Blind or Deaf-</text>
                <text>-and-Dumb</text>
              </label>
            </vblock>
          </hgroup>
          <hgroup  rows ="20"  objecttype="person"  backgroundcolor="#E4DCDC" borderwidth="0" >
            <vblock>
              <input    target="householdReference"  />
            </vblock>
            <vblock>
              <input    target="address"  />
            </vblock>
            <vblock>
              <input    target="fullname"  />
            </vblock>
            <vblock>
              <input    target="roleInHousehold"  />
            </vblock>
            <vblock>
              <input    target="maritalStatus"  />
            </vblock>             
            <vblock>
              <input  target="age:gender=male"  />
            </vblock>
            <vblock>
              <input  target="age:gender=female"  />
            </vblock>
            <vblock>
              <input    target="occupation"  />
            </vblock>
            <vblock>
              <input    target="birthplace"  />
            </vblock>
            <vblock>
              <input    target="note"  />
            </vblock>
          </hgroup>
          <hgroup>
            <vblock>
              <label  colspan="2" >Total of Houses  </label>
            </vblock>
            <vblock/>
            <vblock/>
            <vblock/>
            <vblock/>
            <vblock>
              <input  target="totalMales"  />
            </vblock>
            <vblock>
              <input  target="totalFemales"  />
            </vblock>
            <vblock/>
            <vblock/>
            <vblock/>
          </hgroup>
        </table>
      </certificate>
    </sourcedocument>
  </sourcedocuments>

=== paulagolder/jcert/Certificates/Templates/GRODeathCertCopy_template.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE sourcedocuments  PUBLIC "-//Paul Golder//DTD jcerttemplate//EN" "http://lerot.org/Templates/jcerttemplate.dtd">


  <sourcedocuments>
       <sourcedocument>
         <stylesheet>/Stylesheets/GRODeathCopy_stylesheet.xsl</stylesheet>
         <name>GRO Copy of an entry of Death</name>
         <author>Paul A Golder</author>
         <editdate>9 April 2009</editdate>
          <type>death certificate</type>
          <country>England</country>
          <templateID>GRODeathCopy-0.2</templateID>
              <certificate  objecttype ="certificate"  backgroundcolor="#84E96B"   >
                <hgroup name="heading"  >
                  <hblock>
                    <label >CERTIFIED COPY OF AN ENTRY  OF DEATH</label>
                  </hblock>
                  <hgroup />
                  <hgroup  >
                    <vgroup>
                      <vblock> 
                        <label align="right" >GIVEN AT THE GENERAL REGISTER OFFICE</label>
                      </vblock>
                      <hblock>
                        <label> Application Number</label>
                       <input target="applicationnumber"   width="60" />
                     </hblock>
                   </vgroup>
                 </hgroup>
               </hgroup>
              <hgroup height="50"   borderwidth="0" />
              <vgroup name="main"  borderwidth="1"  padding="10" >
                <hblock height="20">
                  <label width="60"/>
                  <label>REGISTRATION DISTRICT</label>
                  <input    target="district"  />
                </hblock>
                <hblock height="20">
                  <input   target ="year" width="40"/>
                  <label> DEATH in the Sub-district of</label>
                  <input    target="subdistrict" />
                  <label>in the</label>
                  <input     target="county" />
                </hblock>
              </vgroup>
              <table name="deaths"  borderwidth="0" >
                <hgroup>
                <vblock align="center" >
                  <label  verticalalign="top" >
                    <text>Columns:-</text>
                    <text>No.</text>
                  </label>
                </vblock>
                <vblock>
                  <label>
                    <text>1</text>
                    <text>When and.</text>
                    <text>where died</text>
                  </label>
                </vblock>
                <vblock>
                  <label>
                    <text>2</text>
                    <text>Name and Surname.</text>
                  </label>
                </vblock>
                <vblock>
                  <label>
                    <text>3</text>
                    <text>Sex</text>
                  </label>
                </vblock>
                <vblock>
                  <label>
                    <text>4</text>
                    <text>age</text>
                  </label>
                </vblock>
                <vblock>
                  <label>
                    <text>5</text>
                    <text>Occupation.</text>
                  </label>
                </vblock>
                <vblock>
                  <label>
                    <text>6</text>
                    <text>Cause of Death</text>
                  </label>
                </vblock>
                <vblock>
                  <label>
                    <text>7</text>
                    <text>Signature, description and</text>
                    <text>residence of informant</text>
                  </label>
                </vblock>
               <vblock>
                  <label>
                    <text>8</text>
                  <text>When</text>
                  <text>registered</text>
                  </label>
                </vblock>
                <vblock>
                  <label>
                    <text>9</text>
                    <text>Signature of registrar</text>
                  </label>
                </vblock>        
                </hgroup>
                <hgroup  objecttype ="death" >
                <vblock align="center" >
                  <input   target="entryno" />
                </vblock>
                <vblock>
                  <input       target="whenandwhere" />
                </vblock>
                <vblock>
                  <input     target="name" />
                </vblock>
                <vblock>
                  <input     target="gender" />
                </vblock>
                <vblock>
                  <input     target="age" />
                </vblock>
                <vblock>
                  <input     target="occupation" />
                </vblock>
                <vblock>
                  <input     target="causeofdeath" />
                </vblock>
                <vblock>
                  <input     target="informant" />
                </vblock>
               <vblock>
                  <input     target="registrationdate" />
                </vblock>
                <vblock>
                  <input     target="registrar" borderwidth="1" />
                </vblock>
                </hgroup>
              </table>
                         <hgroup height="50"   borderwidth="0" />
              <vgroup  padding="10"   >
                <vblock>
                  <label >CERTIFIED to be a true copy of an entry in the certified copy of a Register of Deaths on the District above mentioned.</label>
                  <label />
                </vblock>
                <hblock>
                  <label  >Given at the GENERAL REGISTER OFFICE under the seal of the said Office, the </label>
                  <input target="issue.day" />
                  <label>day of</label>
                  <input target="issue.month" />
                  <input target ="issue.year" />
                </hblock>
                <hblock name="hline" backgroundcolor="black"  height="5" />
                <hblock>
                  <input target="issue.number"  width="50"/>
                  <label/>
                </hblock>
              </vgroup>
              </certificate>
       </sourcedocument>
  </sourcedocuments>

=== paulagolder/jcert/Certificates/Templates/GROMarriageCertCopy_template.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE sourcedocuments  PUBLIC "-//Paul Golder//DTD jcerttemplate//EN" "http://lerot.org/Templates/jcerttemplate.dtd">


  <sourcedocuments>
       <sourcedocument>
         <stylesheet>Templates/GROMarriageCertCopy_stylesheet.xsl</stylesheet>
         <name>GRO Copy of an entry of marriage</name>
         <author>Paul A Golder</author>
         <editdate>13 April 2009</editdate>
          <type>Marriage certificate</type>
          <savefilepattern>gromarriage.xml</savefilepattern>
          <templateID>engmarriage20090415</templateID>
          <country>England</country>
          <certificate  objecttype="certificate" name="main"  backgroundcolor="#CEF6CE" >    
                <styleblock name="inputcell"  bordercolor="gray"  borderwidth="1"  backgroundcolor="#E4DCDC"  />
                <hgroup name="heading"  >  
                  <vblock>
                          <label  font-size="16"  foregroundcolor="#04B404" >UK Certified Copy of an entry of Marriage</label>
                  </vblock> 
                  <vblock >
                  </vblock>
                    <vgroup align="left">
                      <hblock name ="given"> 
                        <label align="right"  name ="reg"   font-size="16"  foregroundcolor="#04B404" >Given at the General Register Office</label>
                      </hblock>
                      <hblock>
                        <label font-style="italic"   foregroundcolor="black" > Application Number</label>
                       <input target="applicationNumber"   width="60" />
                     </hblock>
                   </vgroup>
                </hgroup>         
              <hgroup height="50" />
              <hgroup objecttype="marriage"  borderwidth="0" >
              <vgroup name="registrationlocation">
                <hblock>
                  <input   target="year"  />
                  <label>Marriage Solemnized at </label>
                  <input   target="location1"/>
                  <label>in the</label>
                  <input   target="location2"  />
                  <label>of</label>
                  <input   target="location3"  />
                  <label>in the county of</label>
                  <input   target="location4"  />
                </hblock>
              </vgroup>
              </hgroup>
              <hgroup height="30"/>
              <table   name="marriage" rows="1" objecttype="marriage"  >
                <hgroup>
                <vblock>
                  <label>No.</label>
                </vblock>
                <vblock>
                  <label>When Married</label>
                </vblock>
                <vblock>
                  <label>Name and Surname</label>
                </vblock>
                <vblock>
                  <label>age</label>
                </vblock>
                <vblock>
                  <label>condition</label>
                </vblock>
                <vblock>
                  <label>Rank or Profession</label>
                </vblock>
                <vblock>
                  <label>Residence at time of marriage</label>
                </vblock>
                <vblock>
                  <label>Fathers name and Surname</label>               
                </vblock>
               <vblock>
                  <label>Rank or Profession of</label>
                  <label>Father</label>
                </vblock>
                </hgroup>
                <hgroup   objecttype="marriage" >
                <vblock>
                  <input      target="entryno" /> 
                </vblock>
                <vblock>
                  <input      target="when" /> 
                </vblock>
                <vblock>
                  <input     target="groom.name" /> 
                  <input      target="bride.name" /> 
                </vblock>
                <vblock>
                  <input      target="groom.age" /> 
                  <input      target="bride.age" />
                </vblock>
                <vblock>
                  <input      target="groom.condition" /> 
                  <input      target="bride.condition" /> 
                </vblock>
                <vblock>
                  <input      target="groom.profession" /> 
                     <input      target="bride.profession" /> 
                </vblock>
                <vblock>
                  <input      target="groom.residence" /> 
                    <input      target="bride.residence" /> 
                </vblock>
                <vblock>          
                  <input      target="groom.father" /> 
                      <input      target="bride.father" /> 
                </vblock>
               <vblock>
                  <input      target="groom.fatheroccupation" /> 
                  <input      target="bride.fatheroccupation" /> 
                </vblock>
                </hgroup>
              </table>
              <hgroup height="30" />
               <vgroup  name="marriagerites"  objecttype="marriage" >
                <hblock  >            
                  <label>Married in the  </label>
                  <input   target="location5"/>
                  <label>according to the Rites and ceremonies of the Established Church, by</label>
                  <input   target="licence"  />
                  <label>or after</label>
                  <input   target="banns"  />
                  <label>by me</label>
                </hblock>   
                <hblock>
                    <vblock />
                    <input width="100" align="right"  target="official"  />
                </hblock>
              </vgroup>    
              <hgroup height="20" />
              <hgroup name="bottomgroup" direction="horizontal"  objecttype="marriage" >
                <vblock>
                  <label  font-size="10" >
                    <text>This marriage</text>
                  <text>was solemnized</text>
                  <text>between us</text>
                  </label>
                </vblock>
                <vblock objecttype="marriage" >
                   <input      target="groom.signature" /> 
                  <input      target="bride.signature" /> 
                </vblock>
                  <vblock>
                  <label  font-size="10" >
                    <text>in the</text>
                  <text>presence</text>
                    <text>of us</text>
                  </label>
                </vblock>
                <vblock>
                   <input      target="witness.first" /> 
                  <input      target="witness.second" /> 
                </vblock>
              </hgroup>       
               <hgroup height="60"   borderwidth="0"  padding="10" />
              <vgroup padding="20" >
                <hblock>
                  <label   foregroundcolor="#04B404" >CERTIFIED to be a true copy of an entry in the certified copy of a Register of Marriages in the Registration Districtof.</label>
                  <input      target="registrationDistrict" /> 
                </hblock>
                <hblock>
                  <label   foregroundcolor="#04B404" >Given at the GENERAL REGISTER OFFICE under the seal of the said Office, the </label>
                  <input target="issue.day" />
                  <label>day of</label>
                  <input target="issue.month" />
                  <input target ="issue.year" />
                </hblock>
              </vgroup>         
          
                <vgroup>
                <hblock>
                  <input target="issue.number"  width="50"/>
                  <label/>
                </hblock>
              </vgroup>
          </certificate>                
       </sourcedocument>
  </sourcedocuments>

=== paulagolder/jcert/Certificates/Templates/GROBirthCertCopy_template.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE sourcedocuments  PUBLIC "-//Paul Golder//DTD jcerttemplate//EN" "http://lerot.org/Templates/jcerttemplate.dtd">


  <sourcedocuments>
       <sourcedocument>
         <stylesheet>/Stylesheets/GROBirthCopy_stylesheet.xsl</stylesheet>
         <name>GRO Copy of an entry of Birth</name>
         <author>Paul A Golder</author>
         <editdate>15 April 2009</editdate>
          <type>Birth certificate</type>
          <country>England</country>
          <templateID>GROBirthCopy-0.2</templateID>
              <certificate  name="top"  objecttype ="certificate"  backgroundcolor="#84E96A"    foregroundcolor="#CB410E" >
                <styleblock name="inputcell"  bordercolor="gray"  borderwidth="1"  backgroundcolor="#E4DCDC"  />
                <hgroup name="heading"  >  
                  <vblock>
                    <label >CERTIFIED COPY OF AN ENTRY OF BIRTH</label>
                  </vblock> 
                  <vblock >
                  </vblock>
                    <vgroup align="left">
                      <hblock name ="given"> 
                        <label align="right"  name ="reg"  >GIVEN AT THE GENERAL REGISTER OFFICE</label>
                      </hblock>
                      <hblock>
                        <label font-style="italic"   foregroundcolor="black" > Application Number</label>
                       <input target="applicationNumber"   width="60" />
                     </hblock>
                   </vgroup>
                </hgroup>
                <hgroup height="10"    >
                </hgroup>
              <vgroup name="certificate"  borderwidth="1"  foregroundcolor="#CB410E"   padding="20">
                <hblock borderwidth="0"  >
                  <label   >REGISTRATION DISTRICT</label>
                  <input    target="district"  />
                </hblock>
                <hblock  borderwidth="0" >
                  <input target ="year"  />
                  <label > BIRTH in the Sub-district of</label>
                  <input    target="subdistrict" />
                  <label >in the</label>
                  <input     target="county" />
                </hblock>
              </vgroup>         
              <table name="births"    borderwidth="1"   foregroundcolor="black"    >
                <hgroup borderwidth="0"  >
                <vblock align="center" >
                  <label  verticalalign="top" >
                    <text>Columns:-</text>
                    <text>No.</text>
                  </label>
                </vblock>
                <vblock>
                  <label>
                    <text>1</text>
                    <text>When and.</text>
                    <text>where born</text>
                  </label>
                </vblock>
                <vblock>
                  <label>
                    <text>2</text>
                    <text>Name if any.</text>
                  </label>
                </vblock>
                <vblock>
                  <label>
                    <text>3</text>
                    <text>Sex</text>
                  </label>
                </vblock>
                <vblock>
                  <label>
                    <text>4</text>
                    <text>Name and Surname</text>
                     <text>of Father</text>
                  </label>
                </vblock>
                <vblock>
                  <label>
                    <text>5</text>
                    <text>Name surname and</text>
                    <text>maiden surname</text>
                    <text>of mother</text>
                  </label>
                </vblock>
                <vblock>
                  <label>
                    <text>6</text>
                    <text>Occupation</text>
                    <text>of Father</text>
                  </label>
                </vblock>
                <vblock>
                  <label>
                    <text>7</text>
                    <text>Signature, description and</text>
                    <text>residence of informant</text>
                  </label>
                </vblock>
               <vblock>
                  <label>
                    <text>8</text>
                  <text>When</text>
                  <text>registered</text>
                  </label>
                </vblock>
                <vblock>
                  <label>
                    <text>9</text>
                    <text>Signature of registrar</text>
                  </label>
                </vblock>   
                <vblock>
                  <label>
                    <text>10</text>
                    <text>Name entered</text>
                    <text>after registration</text>
                  </label>
                </vblock>  
                </hgroup>
                 <hgroup   objecttype ="birth"  borderwidth="0"  >
                <vblock align="center" >
                  <input   target="entryNo" /> 
                </vblock>>
                <vblock>>
                  <input       target="whenAndWhere" /> 
                </vblock>
                <vblock>
                  <input     target="name" /> 
                </vblock>
                <vblock>
                  <input     target="gender" /> 
                </vblock>
                <vblock>
                  <input     target="fathersName" /> 
                </vblock>
                <vblock>
                  <input     target="mothersName" /> 
                </vblock>
                <vblock>
                  <input     target="fathersOccupation" /> 
                </vblock>
                <vblock>
                  <input     target="informant" /> 
                </vblock>
               <vblock>
                  <input     target="registrationDate" /> 
                </vblock>
                <vblock>
                  <input     target="registrar" /> 
                </vblock>   
                <vblock>
                  <input     target="nameEnteredLate" /> 
                </vblock>  
                </hgroup>
              </table>
              <hgroup height="20"  />
              <vgroup  padding="10"   >
                <hblock>
                  <label align="left" >CERTIFIED to be a true copy of an entry in the certified copy of a Register of Births on the District above mentioned.</label>
                  <label  />
                </hblock>
                <hblock>
                  <label  >Given at the GENERAL REGISTER OFFICE under the seal of the said Office, the </label>
                  <input target="issueDay" />
                  <label >day of</label>
                  <input target="issueMonth" />
                  <input target ="issueYear" />
                </hblock>       
                <hblock name="hline" backgroundcolor="red"  height="5"  />
                <hblock>
                  <input target="issueNumber" />
                  <label></label>
                </hblock>
              </vgroup>
              </certificate>
       </sourcedocument>
  </sourcedocuments>
